class Localization {
  static const Map<String, Map<String, String>> _strings = {
    'tr': {
      'role_father': 'Baba',
      'role_mother': 'Anne',
      'role_kid': 'Çocuk',
      'trait_mechanic': 'Tamirci',
      'trait_mechanic_desc': 'Alet kullanımlarında %30 ihtimalle alet kırılmaz.',
      'trait_iron_stomach': 'Demir Mide',
      'trait_iron_stomach_desc': 'Açlığa karşı daha dirençlidir, yavaş acıkır.',
      'trait_protector': 'Koruyucu',
      'trait_protector_desc': 'Keşiflerde daha fazla eşya bulur ama yaralanma riski artar.',
      'trait_big_guy': 'İri Yarı',
      'trait_big_guy_desc': 'Morali çok zor düşer ama daha çabuk susar.',
      'trait_cold_blooded': 'Soğukkanlı',
      'trait_cold_blooded_desc': 'Gece yaşanan kötü olaylardan (hırsız, ses) etkilenmez.',
      'trait_practical': 'Pratik',
      'trait_practical_desc': 'Dışarıdaki keşif görevlerinden 1 gün erken döner.',
      'trait_frugal': 'Tutumlu',
      'trait_frugal_desc': 'Birine çorba içirdiğinde %25 ihtimalle çorba eksilmez.',
      'trait_healer': 'Şifacı',
      'trait_healer_desc': 'Bazen hastalandığında ilaçsız kendiliğinden iyileşebilir.',
      'trait_observer': 'Gözlemci',
      'trait_observer_desc': 'Radyo aramalarında askeri frekans bulma şansı daha yüksektir.',
      'trait_resilient': 'Dirençli',
      'trait_resilient_desc': 'Susuzluğa karşı olağanüstü dayanıklıdır.',
      'trait_agile': 'Çevik',
      'trait_agile_desc': 'Keşif görevlerinde asla yaralanmaz.',
      'trait_cheerful': 'Neşeli',
      'trait_cheerful_desc': 'Onunla sohbet etmek tüm ailenin moralini artırır.',
      'trait_little': 'Ufaklık',
      'trait_little_desc': 'Su ve çorbayı çok daha yavaş tüketir.',
      'trait_lucky': 'Şanslı',
      'trait_lucky_desc': 'Sığınağa saldıran böcek, hırsız gibi belaları kazara savuşturabilir.',
      'trait_sharp_eyed': 'Gözü Açık',
      'trait_sharp_eyed_desc': 'Keşiflerde mutlaka gizli bir ekstra eşya bulur.',

      'loading_wait': 'Lütfen Bekleyin...',
      'start_subtitle': 'Hayatta kalmak için ne kadar ileri gidebilirsin?',
      'start_continue': 'DEVAM ET',
      'start_continue_desc': 'Sığınağa geri dön ve kaldığın yerden devam et.',
      'start_new_gps': 'YENİ OYUN: GERÇEKÇİ OYNANIŞ',
      'start_new_gps_desc': 'Tam konumunu haritalandırır.',
      'start_new_ip': 'YENİ OYUN: HIZLI OYNANIŞ',
      'start_new_ip_desc': 'İzin gerektirmez. Tahmini harita üzerinden ilerler.',
      'lang_tr': 'TR',
      'lang_en': 'EN',
      
      'loading_radar': 'Radar Açılıyor...',
      'loading_map_cache': 'Harita Hafızadan Yükleniyor...',
      'loading_map_api': 'Gerçek Dünya Verileri Çekiliyor (API)...',
      'loading_map_fallback': 'Sinyal Zayıf. Tahmini Harita Kullanılıyor...',
      
      'pharmacy_1': 'Şifa Eczanesi',
      'pharmacy_2': 'Merkez Eczanesi',
      'pharmacy_3': 'Sağlık Eczanesi',
      'pharmacy_4': 'Umut Eczanesi',
      'pharmacy_5': 'Hayat Eczanesi',
      'pharmacy_6': 'Güneş Eczanesi',
      'pharmacy_7': 'Halk Eczanesi',
      'pharmacy_8': 'Yeni Eczane',
      'market_1': 'Güven Süpermarket',
      'market_2': 'Büyük Gıda',
      'market_3': 'Kardeşler Bakkalı',
      'market_4': 'Ucuza Market',
      'market_5': 'Bereket Gıda',
      'market_6': 'Merkez Hipermarket',
      'market_7': 'Bizim Bakkal',
      'market_8': 'Köşe Market',
      'hardware_1': 'Usta Nalburiye',
      'hardware_2': 'Yapı Market',
      'hardware_3': 'Çınar Hırdavat',
      'hardware_4': 'Emin Yapı',
      'hardware_5': 'Kardeşler Nalbur',

      'place_military': 'Askeri Tahliye Noktası',
      'place_utopia': 'Gizli Yeraltı Kolonisi (Giriş için 5 Su/5 Çorba)',
      'expedition_ambush': 'KÖTÜ HABER! {char}, dönüş yolunda yağmacıların pususuna düştü. Yaralı döndü!',
      'expedition_empty': '{char} sığınağa döndü. Gittiği bölge ({dest}) yağmalanmış, bir şey bulamadı.',
      'expedition_success_market': 'BAŞARI! {char} marketinden {water} su ve {soup} çorba getirdi!',
      'expedition_success': 'BAŞARI! {char} yanına {water} su ve {soup} çorba getirdi!',
      'death_msg': 'KÖTÜ HABER! Bu sabah uyandığımızda {names} nefes almıyordu. Açlık ve susuzluğa daha fazla dayanamadı...\n\n',

      'event_army_fake': "Dışarıdan sesler geliyor! Kapağa vuruyorlar. 'Ordu Birlikleri, açın!' Kurtulduk mu?",
      'action_open_hatch': "Kapağı Aç",
      'event_roaches': "Devasa, parlayan mutant hamamböcekleri çorba kutularımıza saldırıyor!",
      'event_roaches_killed': "Hepsini ezerek öldürdük. Eşyalarımız güvende.",
      'event_roaches_left': "Böcekler konserveleri açamayıp kendi kendilerine gittiler! Şanslıyız.",
      'event_roaches_stole': "Böcekler 2 çorbamızı yiyip uzaklaştı...",
      'event_vent_broken': "Sığınağın havalandırması bozuldu. İçeriye zehirli hava sızıyor.",
      'event_vent_fixed': "Zor oldu ama tamir ettik. Ciğerlerimiz bayram etti.",
      'event_vent_sick': "Hava kalitesi çok kötü, herkes hastalandı.",
      'event_raiders': "GÜM! GÜM! Gece vakti sığınak kapağı yumruklanıyor. Seslerden anladığımız kadarıyla yağmacılar!",
      'event_raiders_scared': "Havaya bir el ateş ettik. Adım sesleri koşarak uzaklaştı.",
      'event_raiders_stole': "Kapağı kırıp içeri daldılar! Erzaklarımızın bir kısmını (2 Su, 2 Çorba) çalıp gittiler.",
      'event_gas_leak': "Duvardaki eski borulardan şiddetli bir tıslama sesi geliyor. Sığınağa boğucu bir gaz sızıyor!",
      'action_plug_rags': "Bezlerle Tıka",
      'event_gas_tired': "Bütün gece zehirli gazı soluyarak borudaki çatlağı bezlerle tıkamaya çalıştık. Sızıntı durdu ama çok yorulduk, birimiz hastalandı.",
      'event_sus_cans': "Köşedeki kutuların arkasında kapağı şişkin ve etiketi silinmiş iki konserve bulduk. Erzaklarımıza ekleyelim mi?",
      'action_add_stock': "Stoğa Ekle",
      'event_cans_good': "Konserveler hala sağlammış! Gıdamız arttı (+2 Çorba).",
      'event_cans_bad': "Kötü fikirdi. Kutular delikmiş, sızan pis koku birimizi hasta etti.",
      'action_throw_away': "Çöpe At",
      'event_cans_thrown': "Riske girmeye değmez. Çöpe attık.",
      'event_madness': "Sığınağın karanlığı ve sessizliği yavaş yavaş akıl sağlığımızı etkiliyor. Biri köşede kendi kendine konuşuyor.",
      'event_madness_cured': "Eski günlerden, güzel anılardan bahsettik. Zor oldu ama toparlandık.",
      'log_quiet_day': "{day}. Gün. Sığınakta sessiz bir bekleyiş sürüyor. Kaynakları idareli kullanmalıyız.",
      'log_expedition_start': "{char}, {dest} bölgesine yola çıktı. Umarım sağ döner.",
      'ending_heli': "İnanamıyorum! Kurtarma helikopteri sığınağın tam üzerine indi! {char} yolu açtı. BAŞARDIK, KURTULDUK!",
      'ending_utopia': "Erzaklarımızı sırtlandık ve {char} rehberliğinde Gizli Yeraltı Kolonisine ulaştık. Burada yeni bir hayat başlıyor. KAZANDINIZ!",
      'ending_utopia_fail': "HAYAL KIRIKLIĞI! {char} koloniyi buldu ama içeri kabul edilmemiz için yanımızda en az 5 Su ve 5 Çorba götürmemiz gerektiğini söylediler. Erzak yetersizliğinden geri çevrildik.",
      'expedition_success_pharmacy': "BAŞARI! {char} eczaneden İlk Yardım Kiti ve Su buldu!",
      'expedition_success_hardware': "BAŞARI! {char} nalburdan Alet Çantası buldu!",
      'error_cache_read': "Önbellek okuma hatası: {e}",
      'unknown_region': "Bilinmeyen Bölge",
      'event_all_dead': 'Herkes öldü... Sığınak artık sessiz bir mezar.',
      'event_char_outside': '{desc}\n\n{char} hala dışarıda, dönmesini bekliyoruz.',
      'event_radio_safe': "TELSİZ: {char} terk edilmiş bir dükkanda kilitli bir çelik kasa buldu. Açmayı denesin mi?",
      'action_force_tool': 'Aletle Zorla (Alet)',
      'event_safe_opened': 'Kasa açıldı! İçinden 2 Su ve 2 Çorba çıktı. {char} yola devam ediyor.',
      'action_leave_silently': 'Sessizce Bırak',
      'event_safe_left': 'Riski göze almadık. {char} sessizce keşfe devam ediyor.',
      'event_radio_stranger': "TELSİZ: {char} yolda yaralı, çaresiz bir yabancıya rastladı. Telsizden 'Ona yardım edeyim mi?' diye soruyor.",
      'action_give_water': 'Su Ver (-1 Su)',
      'event_stranger_utopia': "Yabancı suyu içti ve minnettarlıkla bize kendi kendine yetebilen efsanevi 'Ütopya' kolonisinin koordinatlarını verdi! Haritaya eklendi.",
      'event_stranger_medkit': 'Yabancı minnettarlıkla çantasındaki son İlk Yardım Kitini bize verdi.',
      'action_ignore': 'Görmezden Gel',
      'event_stranger_ignored': 'Acımasız bir dünyadayız. Yabancıyı ölüme terk edip yola devam ettik. (Herkesin morali düştü)',
      'event_radio_trader': 'TELSİZ: {char} dost canlısı görünen bir hayatta kalanla karşılaştı. 2 Çorba karşılığında 1 İlk Yardım Kiti takası teklif ediyor.',
      'action_trade': 'Takas Yap (-2 Çorba)',
      'event_trade_success': 'Takas başarılı! İlk Yardım Kiti envantere eklendi.',
      'event_trade_rejected': 'Teklifi reddettik. Karakterimiz kendi yoluna gitti.',
      'log_first_day': 'Sığınağa ulaştık. Şimdilik güvendeyiz. Bombanın sesi kulaklarımızı sağır edecek gibiydi. Dışarı çıkamayız.',
      'log_first_night': 'İlk gece çok zordu. Yukarıdan garip tıkırtılar duyduk. Ampul sürekli göz kırpıyor.',
      'radio_military_found': "RADYODA NET BİR SİNYAL! 'Hayatta kalanlar, yakınlardaki Askeri Tahliye Noktasına gelin. Kurtarma ekipleri hazır.' Haritaya eklendi!",
      'radio_signal_lost': "Radyodan parazitli bir ses geliyor... 'Orada kimse var mı? Lütfen yardım edin...' Ses aniden kesildi.",
      'radio_military_hope': "Askeri bir frekans yakaladık! 'Sektör 4 temiz. Beklemede kalın.' Bizim için umut olabilir.",
      'radio_static': 'Sadece parazit ve statik elektrik sesi var. Dışarıda kimse kalmamış gibi...',
      'radio_music_good': 'Garip bir müzik kanalı bulduk. Çalan şarkı savaş öncesi günleri hatırlattı. Herkesin morali biraz olsun yerine geldi.',
      'radio_music_classic': 'Radyoyu sadece müzik dinlemek için açtık. Klasik müzik sığınağın soğuk duvarlarında yankılandı. Moraller düzeldi.',
      'ending_army': 'Dışarıdan kapı zorlandı! Askerler içeri girdi. Başardık, kurtulduk!',
      'action_crush_tool': 'Aletle Ez',
      'action_fix_tool': 'Tamir Et (Alet)',
      'action_dont_fix': 'Tamir Etme',
      'action_scare_gun': 'Havaya Ateş Et (Cephane)',
      'action_wait_silently': 'Sessizce Bekle',
      'action_chat_long': 'Uzun Uzun Sohbet Et',
      'gps_location': 'GPS Konumu',
      'ip_error': 'IP Hata: {e}',
      'ui_use_medkit': 'Medkit Kullan (-1 Medkit)',
      'ui_chat': 'Sohbet Et',
      'ui_target_not_found': 'HEDEF BULUNAMADI',
      'ui_scan_signal_btn': 'Sinyal Tara',
      'ui_black_market': 'KARABORSA / DESTEK',
      'ui_emergency_signal': 'Acil Durum Sinyali',
      'ui_survival_pack': 'Hayatta Kalma Paketi (\$1)',
      'ui_confirm': 'Onayla',
      'ui_close': 'Kapat',
      'ui_radio': 'RADYO',
      'ui_guide': 'REHBER',
      'ui_success': 'BAŞARILI',
      'ui_restore_success': 'Satın alımlarınız başarıyla geri yüklendi! Reklamlar kaldırıldı.',
      'ui_info': 'BİLGİ',
      'ui_restore_fail': 'Geri yüklenecek aktif bir satın alım bulunamadı.',
      'ui_conn_error': 'BAĞLANTI HATASI',
      'ui_conn_error_desc': 'Sunucuyla iletişim kurulamadı. İnternetinizi kontrol edin.',
      'ui_signal_lost': 'SİNYAL KESİLDİ',
      'ui_days_survived': 'HAYATTA KALINAN GÜN',
      'ui_back_to_menu': 'ANA MENÜYE DÖN',
      'ui_bunker_days': 'SIĞINAKTA GEÇEN GÜN',
      'ui_give_water': 'Su İçir (-1 Su)',
      'ui_give_water_desc': 'Susuzluğunu giderir.',
      'ui_give_soup': 'Çorba Yedir (-1 Çorba)',
      'ui_give_soup_desc': 'Açlığını giderir.',
      'ui_give_medkit_desc': 'Hastalığı/Yarayı iyileştirir.',
      'ui_chat_desc': 'Moralini yükseltir. (Günde 1 kez)',
      'ui_day_counter': 'GÜN {day}',
      'ui_soup': 'Çorba',
      'ui_medkit': 'İlk Yardım Kiti',
      'ui_tool': 'Alet Çantası',
      'ui_store': 'MAĞAZA',
      'ui_logs': 'GÜNLÜK KAYITLARI',
      'ui_expedition_ongoing': 'KEŞİF SÜRÜYOR',
      'ui_expedition_start': 'KEŞFE ÇIK',
      'ui_end_day': 'GÜNÜ BİTİR',
      'ui_plan_expedition': 'Keşif Görevi Planla',
      'ui_select_target': 'Hedef Seçimi',
      'ui_select_char': 'Gönderilecek Karakter',
      'ui_cancel': 'İptal',
      'ui_please_select_target': 'Lütfen haritadan göndermek istediğiniz mekanı seçin.',
      'ui_radio_title': 'AMATÖR RADYO K6JFD',
      'ui_radio_desc': 'Dış dünyadan bir ses duymak veya sadece biraz müzik dinlemek, sığınaktaki herkesin ruh halini etkileyebilir. Günde sadece bir kez kullanabiliriz.',
      'ui_scan_signal': 'Askeri veya sivil yayınları ara.',
      'ui_listen_music': 'Müzik Dinle',
      'ui_listen_music_desc': 'Eski şarkılar moralleri yükseltir.',
      'ui_store_desc': 'Dışarıdan veya havadan gelen destek paketleriyle sığınaktaki ömrünü uzat. Telsizle sipariş veriyoruz.',
      'ui_watch_ad_desc': 'Kısa bir video izle. Ödül: +1 Su, +1 Çorba.',
      'ui_ad_cooldown': 'Sinyal şarj oluyor. {days} gün sonra tekrar kullanılabilir.',
      'ui_signal_received': 'SİNYAL ALINDI',
      'ui_ad_reward': 'Destek ulaştı! +1 Su, +1 Çorba kazanıldı.',
      'ui_ad_fail': 'Bağlantı kurulamadı veya reklam yüklenemedi. Lütfen internetinizi kontrol edin.',
      'ui_buy_pack_desc': '+5 Su, +5 Çorba, +2 İlk Yardım, +2 Cephane.',
      'ui_cargo_arrived': 'KARGO ULAŞTI',
      'ui_pack_bought': 'Paket Satın Alındı! Tüm kaynaklar sığınağa eklendi.',
      'ui_transaction_cancel': 'İŞLEM İPTAL',
      'ui_transaction_cancel_desc': 'Satın alma işlemi tamamlanamadı veya iptal edildi.',
      'ui_elite_active': 'Elit Sığınak (Aktif)',
      'ui_elite_buy': 'Elit Sürüm (\$5)',
      'ui_elite_desc_active': 'Zorunlu reklamlar kaldırıldı.',
      'ui_elite_desc_buy': 'Zorunlu reklamları kalıcı olarak kaldır. Bonus: +1 Alet.',
      'ui_elite_success': 'ELİT SÜRÜM AKTİF',
      'ui_elite_success_desc': 'Tebrikler! Reklamlar kaldırıldı ve +1 Alet eklendi.',
      'ui_guide_title': 'HAYATTA KALMA REHBERİ',
      'ui_guide_1': '1. TEMEL AMACINIZ',
      'ui_guide_1_desc': 'Sığınakta ailenizle birlikte olabildiğince uzun süre hayatta kalmak. Su ve çorba stoklarınızı akıllıca yönetin. Günleri atlatmak için sağ alttaki \'Günü Bitir\' butonunu kullanın. Açlık ve susuzluk karakterleri hastalandırır, yalnızlık delirtir. Herkes ölürse oyun biter.',
      'ui_guide_2': '2. KEŞİF SİSTEMİ (GERÇEK DÜNYA HARİTASI)',
      'ui_guide_2_desc': 'Oyun, cihazınızın konumunu kullanarak etrafınızdaki gerçek dünyayı haritalandırır. \'Keşfe Çık\' diyerek karakterlerinizi Eczane, Market veya Nalbur gibi yakınınızdaki noktalara erzak toplamaya gönderebilirsiniz. Dışarıdaki tehlikeli olaylara ve yağmacılara karşı dikkatli olun!',
      'ui_guide_3': '3. KARAKTER YETENEK (TRAIT) SİSTEMİ',
      'ui_guide_3_desc': 'Ailenin her üyesi oyuna tamamen rastgele yeteneklerle (örn: Demir Mide, Şifacı, Çevik) başlar. Karakterlerinizin portresine tıklayarak durumlarını görün, yemek/su verin, medkit kullanın veya sohbet ederek morallerini yüksek tutun.',
      'ui_guide_4': '4. KAYNAK VE ENVANTER YÖNETİMİ',
      'ui_guide_4_desc': '• Su & Çorba: Temel yaşam kaynağıdır.\n• İlk Yardım Kiti (Medkit): Hastalık ve yaralanmaları anında iyileştirir.\n• Alet Çantası (Tool): Havalandırma gibi sığınak arızalarını tamir etmenizi veya keşiflerdeki kilitli kasaları açmanızı sağlar.\n• Cephane: Gece sığınağa saldıran yağmacıları veya yaratıkları savuşturmak için şarttır.',
      'ui_guide_5': '5. RADYO VE GİZLİ SONLAR',
      'ui_guide_5_desc': 'Kurtuluş için tek yol sığınakta çürümek değil! Günde bir kez radyoyu kullanarak askeri frekansları arayabilir (Sinyal Tara) veya müzik dinleyerek moralleri düzeltebilirsiniz. Askeri tahliye noktalarını bularak veya gizemli \'Ütopya\' kolonisine giden yolu açarak ailenizi kurtarın.',
      'ui_guide_ready': 'Anladım, Hayatta Kalmaya Hazırım',
      'ui_settings': 'AYARLAR',
      'ui_music_vol': 'Müzik Sesi',
      'ui_sfx_vol': 'Efekt Sesi',
      'ui_restore_purchases': 'Satın Alımları Geri Yükle',
      'ui_restore_desc': 'Elit Sürüm lisansını kurtarır.',
      'ui_send_feedback': 'Geri Bildirim Gönder',
      'ui_feedback_desc': 'Bize düşüncelerinizi iletin.',
      'ui_day_ended': 'GÜN {day} BİTTİ',
    },
    'en': {
      'role_father': 'Father',
      'role_mother': 'Mother',
      'role_kid': 'Kid',
      'trait_mechanic': 'Mechanic',
      'trait_mechanic_desc': '30% chance tools won\'t break when used.',
      'trait_iron_stomach': 'Iron Stomach',
      'trait_iron_stomach_desc': 'More resistant to hunger, gets hungry slower.',
      'trait_protector': 'Protector',
      'trait_protector_desc': 'Finds more items on expeditions but injury risk increases.',
      'trait_big_guy': 'Big Guy',
      'trait_big_guy_desc': 'Morale drops very slowly but gets thirsty faster.',
      'trait_cold_blooded': 'Level-headed',
      'trait_cold_blooded_desc': 'Remains calm and is not affected by bad night events (thief, noise).',
      'trait_practical': 'Practical',
      'trait_practical_desc': 'Returns 1 day early from outside expeditions.',
      'trait_frugal': 'Frugal',
      'trait_frugal_desc': '25% chance soup won\'t be consumed when feeding someone.',
      'trait_healer': 'Healer',
      'trait_healer_desc': 'Sometimes heals naturally without medicine when sick.',
      'trait_observer': 'Observer',
      'trait_observer_desc': 'Higher chance to find military frequencies on radio.',
      'trait_resilient': 'Resilient',
      'trait_resilient_desc': 'Extraordinarily resistant to thirst.',
      'trait_agile': 'Agile',
      'trait_agile_desc': 'Never gets injured on expeditions.',
      'trait_cheerful': 'Cheerful',
      'trait_cheerful_desc': 'Talking with them increases the whole family\'s morale.',
      'trait_little': 'Little One',
      'trait_little_desc': 'Consumes water and soup much slower.',
      'trait_lucky': 'Lucky',
      'trait_lucky_desc': 'Can accidentally fend off threats like bugs or thieves.',
      'trait_sharp_eyed': 'Sharp-eyed',
      'trait_sharp_eyed_desc': 'Always finds a hidden extra item on expeditions.',

      'loading_wait': 'Please Wait...',
      'start_subtitle': 'How far can you go to survive?',
      'start_continue': 'CONTINUE',
      'start_continue_desc': 'Return to the bunker and resume your game.',
      'start_new_gps': 'NEW GAME: REALISTIC',
      'start_new_gps_desc': 'Maps your exact location.',
      'start_new_ip': 'NEW GAME: FAST START',
      'start_new_ip_desc': 'No permissions needed. Uses estimated map.',
      'lang_tr': 'TR',
      'lang_en': 'EN',
      
      'loading_radar': 'Initializing Radar...',
      'loading_map_cache': 'Loading Map from Cache...',
      'loading_map_api': 'Fetching Real-World Data (API)...',
      'loading_map_fallback': 'Weak Signal. Using Estimated Map...',

      'pharmacy_1': 'Healing Pharmacy',
      'pharmacy_2': 'Central Pharmacy',
      'pharmacy_3': 'Health Pharmacy',
      'pharmacy_4': 'Hope Pharmacy',
      'pharmacy_5': 'Life Pharmacy',
      'pharmacy_6': 'Sun Pharmacy',
      'pharmacy_7': 'Public Pharmacy',
      'pharmacy_8': 'New Pharmacy',
      'market_1': 'Trust Supermarket',
      'market_2': 'Big Grocery',
      'market_3': 'Brothers Grocery',
      'market_4': 'Cheap Market',
      'market_5': 'Blessing Grocery',
      'market_6': 'Central Hypermarket',
      'market_7': 'Our Grocery',
      'market_8': 'Corner Market',
      'hardware_1': 'Master Hardware',
      'hardware_2': 'Build Market',
      'hardware_3': 'Plane Hardware',
      'hardware_4': 'Sure Build',
      'hardware_5': 'Brothers Hardware',

      'place_military': 'Military Evacuation Point',
      'place_utopia': 'Secret Underground Colony (Entry: 5 Water/5 Soup)',
      'expedition_ambush': 'BAD NEWS! {char} was ambushed by raiders on the way back. Returned injured!',
      'expedition_empty': '{char} returned to the bunker. The {dest} was already looted, found nothing.',
      'expedition_success_market': 'SUCCESS! {char} brought back {water} water and {soup} soup from the market!',
      'expedition_success': 'SUCCESS! {char} brought back {water} water and {soup} soup!',
      'death_msg': 'BAD NEWS! When we woke up this morning, {names} were not breathing. They couldn\'t survive the hunger and thirst...\n\n',

      'event_army_fake': "Voices from outside! They are hitting the hatch. 'Army units, open up!' Are we saved?",
      'action_open_hatch': "Open Hatch",
      'event_roaches': "Giant, glowing mutant cockroaches are attacking our soup cans!",
      'event_roaches_killed': "We crushed them all. Our supplies are safe.",
      'event_roaches_left': "The bugs couldn't open the cans and left on their own! We're lucky.",
      'event_roaches_stole': "The bugs ate 2 of our soups and left...",
      'event_vent_broken': "The bunker's ventilation broke down. Toxic air is leaking in.",
      'event_vent_fixed': "It was hard but we fixed it. We can finally breathe again.",
      'event_vent_sick': "Air quality is terrible, everyone got sick.",
      'event_raiders': "BANG! BANG! The bunker hatch is being pounded at night. Sounds like raiders!",
      'event_raiders_scared': "We fired a shot into the air. The footsteps ran away.",
      'event_raiders_stole': "They broke the hatch and rushed in! They stole some of our supplies (2 Water, 2 Soup).",
      'event_gas_leak': "A loud hissing sound is coming from the old pipes on the wall. Choking gas is leaking into the bunker!",
      'action_plug_rags': "Plug with Rags",
      'event_gas_tired': "We spent all night breathing toxic gas trying to plug the crack with rags. The leak stopped but we're exhausted, one of us got sick.",
      'event_sus_cans': "We found two unlabelled cans with bulging lids behind the boxes in the corner. Should we add them to our supplies?",
      'action_add_stock': "Add to Stock",
      'event_cans_good': "The cans are still good! Our food increased (+2 Soup).",
      'event_cans_bad': "Bad idea. The cans were punctured, the foul smell made one of us sick.",
      'action_throw_away': "Throw Away",
      'event_cans_thrown': "Not worth the risk. We threw them away.",
      'event_madness': "The dark and silence of the bunker is slowly affecting our sanity. Someone is talking to themselves in the corner.",
      'event_madness_cured': "We talked about the good old days. It was hard but we pulled through.",
      'log_quiet_day': "Day {day}. A quiet wait continues in the bunker. We must use our resources sparingly.",
      'log_expedition_start': "{char} headed out to the {dest}. Hope they return safely.",
      'ending_heli': "I can't believe it! A rescue helicopter landed right on the bunker! {char} cleared the way. WE DID IT, WE'RE SAVED!",
      'ending_utopia': "We packed our supplies and reached the Secret Underground Colony guided by {char}. A new life begins here. YOU WON!",
      'ending_utopia_fail': "DISAPPOINTMENT! {char} found the colony but they said we need at least 5 Water and 5 Soup to be accepted. We were turned away due to lack of supplies.",
      'expedition_success_pharmacy': "SUCCESS! {char} found a Medkit and Water at the pharmacy!",
      'expedition_success_hardware': "SUCCESS! {char} found a Tool at the hardware store!",
      'error_cache_read': "Cache read error: {e}",
      'unknown_region': "Unknown Region",
      'event_all_dead': 'Everyone died... The bunker is now a silent tomb.',
      'event_char_outside': '{desc}\n\n{char} is still outside, we are waiting for their return.',
      'event_radio_safe': "RADIO: {char} found a locked steel safe in an abandoned shop. Should they try to open it?",
      'action_force_tool': 'Force Open (Tool)',
      'event_safe_opened': 'Safe opened! Found 2 Water and 2 Soup. {char} continues on.',
      'action_leave_silently': 'Leave Silently',
      'event_safe_left': 'We did not take the risk. {char} quietly continues exploring.',
      'event_radio_stranger': "RADIO: {char} came across an injured, helpless stranger on the road. Asking 'Should I help them?' over the radio.",
      'action_give_water': 'Give Water (-1 Water)',
      'event_stranger_utopia': "The stranger drank the water and gratefully gave us the coordinates of the self-sufficient legendary 'Utopia' colony! Added to map.",
      'event_stranger_medkit': 'The stranger gratefully gave us the last Medkit in their bag.',
      'action_ignore': 'Ignore',
      'event_stranger_ignored': 'We are in a cruel world. We left the stranger to die and moved on. (Everyone\'s morale dropped)',
      'event_radio_trader': 'RADIO: {char} encountered a friendly-looking survivor. They offer to trade 1 Medkit for 2 Soups.',
      'action_trade': 'Trade (-2 Soup)',
      'event_trade_success': 'Trade successful! Medkit added to inventory.',
      'event_trade_rejected': 'We rejected the offer. Our character went their own way.',
      'log_first_day': 'We reached the bunker. Safe for now. The sound of the bomb was deafening. We cannot go outside.',
      'log_first_night': 'The first night was very hard. Heard strange clicking sounds from above. The light bulb keeps flickering.',
      'radio_military_found': "CLEAR SIGNAL ON RADIO! 'Survivors, proceed to the nearby Military Evacuation Point. Rescue teams are ready.' Added to map!",
      'radio_signal_lost': "Static voice on the radio... 'Is anyone there? Please help...' The signal suddenly cut off.",
      'radio_military_hope': "Caught a military frequency! 'Sector 4 clear. Stand by.' There might be hope for us.",
      'radio_static': 'Only static and white noise. It feels like no one is left out there...',
      'radio_music_good': 'Found a strange music channel. The song playing reminded us of pre-war days. Everyone\'s morale recovered slightly.',
      'radio_music_classic': 'We turned on the radio just to listen to music. Classical music echoed on the cold walls of the bunker. Morale improved.',
      'ending_army': 'The door was forced from the outside! Soldiers breached in. We did it, we are saved!',
      'action_crush_tool': 'Smash with Tool',
      'action_fix_tool': 'Fix (Tool)',
      'action_dont_fix': 'Do Not Fix',
      'action_scare_gun': 'Fire Warning Shot (Ammo)',
      'action_wait_silently': 'Wait Silently',
      'action_chat_long': 'Have a Long Chat',
      'gps_location': 'GPS Location',
      'ip_error': 'IP Error: {e}',
      'ui_use_medkit': 'Use Medkit (-1 Medkit)',
      'ui_chat': 'Chat',
      'ui_target_not_found': 'TARGET NOT FOUND',
      'ui_scan_signal_btn': 'Scan Signal',
      'ui_black_market': 'BLACK MARKET / SUPPORT',
      'ui_emergency_signal': 'Emergency Signal',
      'ui_survival_pack': 'Survival Pack (\$1)',
      'ui_confirm': 'Confirm',
      'ui_close': 'Close',
      'ui_radio': 'RADIO',
      'ui_guide': 'GUIDE',
      'ui_success': 'SUCCESS',
      'ui_restore_success': 'Purchases restored successfully! Ads removed.',
      'ui_info': 'INFO',
      'ui_restore_fail': 'No active purchase found to restore.',
      'ui_conn_error': 'CONNECTION ERROR',
      'ui_conn_error_desc': 'Could not connect to the server. Check your internet.',
      'ui_signal_lost': 'SIGNAL LOST',
      'ui_days_survived': 'DAYS SURVIVED',
      'ui_back_to_menu': 'BACK TO MENU',
      'ui_bunker_days': 'DAYS IN BUNKER',
      'ui_give_water': 'Give Water (-1 Water)',
      'ui_give_water_desc': 'Quenches thirst.',
      'ui_give_soup': 'Give Soup (-1 Soup)',
      'ui_give_soup_desc': 'Satisfies hunger.',
      'ui_give_medkit_desc': 'Heals sickness/injury.',
      'ui_chat_desc': 'Boosts morale. (Once a day)',
      'ui_day_counter': 'DAY {day}',
      'ui_soup': 'Soup',
      'ui_medkit': 'Medkit',
      'ui_tool': 'Tool',
      'ui_store': 'STORE',
      'ui_logs': 'LOGS',
      'ui_expedition_ongoing': 'ON EXPEDITION',
      'ui_expedition_start': 'EXPEDITION',
      'ui_end_day': 'END DAY',
      'ui_plan_expedition': 'Plan Expedition',
      'ui_select_target': 'Select Target',
      'ui_select_char': 'Select Character',
      'ui_cancel': 'Cancel',
      'ui_please_select_target': 'Please select a location from the map to explore.',
      'ui_radio_title': 'AMATEUR RADIO K6JFD',
      'ui_radio_desc': 'Hearing a voice from the outside world or just listening to some music can affect everyone\'s mood in the bunker. We can only use it once a day.',
      'ui_scan_signal': 'Scan for military or civilian broadcasts.',
      'ui_listen_music': 'Listen to Music',
      'ui_listen_music_desc': 'Old songs boost morale.',
      'ui_store_desc': 'Extend your life in the bunker with supply drops from the outside or air. We order via radio.',
      'ui_watch_ad_desc': 'Watch a short video. Reward: +1 Water, +1 Soup.',
      'ui_ad_cooldown': 'Signal recharging. Available in {days} days.',
      'ui_signal_received': 'SIGNAL RECEIVED',
      'ui_ad_reward': 'Supplies arrived! +1 Water, +1 Soup gained.',
      'ui_ad_fail': 'Could not connect or load ad. Please check your internet.',
      'ui_buy_pack_desc': '+5 Water, +5 Soup, +2 Medkits, +2 Ammo.',
      'ui_cargo_arrived': 'CARGO ARRIVED',
      'ui_pack_bought': 'Package Bought! All resources added to bunker.',
      'ui_transaction_cancel': 'TRANSACTION CANCELLED',
      'ui_transaction_cancel_desc': 'The purchase could not be completed or was cancelled.',
      'ui_elite_active': 'Elite Bunker (Active)',
      'ui_elite_buy': 'Elite Edition (\$5)',
      'ui_elite_desc_active': 'Forced ads removed.',
      'ui_elite_desc_buy': 'Permanently remove forced ads. Bonus: +1 Tool.',
      'ui_elite_success': 'ELITE EDITION ACTIVE',
      'ui_elite_success_desc': 'Congratulations! Ads removed and +1 Tool added.',
      'ui_guide_title': 'SURVIVAL GUIDE',
      'ui_guide_1': '1. YOUR MAIN GOAL',
      'ui_guide_1_desc': 'Survive as long as possible with your family in the bunker. Manage your water and soup stocks wisely. Use the \'End Day\' button on the bottom right to pass days. Hunger and thirst make characters sick, loneliness drives them mad. If everyone dies, the game is over.',
      'ui_guide_2': '2. EXPEDITION SYSTEM (REAL WORLD MAP)',
      'ui_guide_2_desc': 'The game maps the real world around you using your device\'s location. By clicking \'Expedition\', you can send your characters to nearby spots like Pharmacy, Market, or Hardware store to gather supplies. Beware of dangerous events and raiders outside!',
      'ui_guide_3': '3. CHARACTER TRAIT SYSTEM',
      'ui_guide_3_desc': 'Every family member starts the game with completely random traits (e.g. Iron Stomach, Healer, Agile). Click on their portrait to see their status, give them food/water, use medkits, or chat to keep their morale high.',
      'ui_guide_4': '4. RESOURCE AND INVENTORY MANAGEMENT',
      'ui_guide_4_desc': '• Water & Soup: Basic life source.\n• Medkit: Instantly heals sickness and injuries.\n• Tool: Allows you to fix bunker breakdowns like ventilation or open locked safes on expeditions.\n• Ammo: Essential for fending off raiders or creatures attacking the bunker at night.',
      'ui_guide_5': '5. RADIO AND SECRET ENDINGS',
      'ui_guide_5_desc': 'Rotting in the bunker isn\'t the only way out! Use the radio once a day to scan for military frequencies or listen to music to fix morale. Save your family by finding military evacuation points or opening the way to the mysterious \'Utopia\' colony.',
      'ui_guide_ready': 'Understood, I am ready to survive',
      'ui_settings': 'SETTINGS',
      'ui_music_vol': 'Music Volume',
      'ui_sfx_vol': 'SFX Volume',
      'ui_restore_purchases': 'Restore Purchases',
      'ui_restore_desc': 'Restores Elite Edition license.',
      'ui_send_feedback': 'Send Feedback',
      'ui_feedback_desc': 'Let us know your thoughts.',
      'ui_day_ended': 'DAY {day} ENDED',
    }
  };

  static String t(String key, String lang, [Map<String, String>? args]) {
    String text = _strings[lang]?[key] ?? _strings['tr']?[key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    return text;
  }
}
