import 'package:shared_preferences/shared_preferences.dart';

class Loc {
  static String currentLang = 'tr';

  static final Map<String, Map<String, String>> _strings = {
    'tr': {
      'app_name': 'BUNKER 06',
      'subtitle_tagline': 'Hayatta kalmak iÃ§in ne kadar ileri gidebilirsin?',
      'btn_continue': 'DEVAM ET',
      'btn_continue_sub': 'SÄ±ÄŸÄ±naÄŸa geri dÃ¶n ve kaldÄ±ÄŸÄ±n yerden devam et.',
      'btn_new_real': 'YENÄ° OYUN: GERÃ‡EKÃ‡Ä° OYNANIÅ',
      'btn_new_real_sub': 'Tam konumunu haritalandÄ±rÄ±r.',
      'btn_new_fast': 'YENÄ° OYUN: HIZLI OYNANIÅ',
      'btn_new_fast_sub': 'Ä°zin gerektirmez. Tahmini harita Ã¼zerinden ilerler.',
      'loading_please_wait': 'LÃ¼tfen Bekleyin...',
      'tab_radio': 'RADYO',
      'tab_store': 'MAÄAZA',
      'tab_guide': 'REHBER',
      'settings_title': 'AYARLAR',
      'settings_bgm': 'MÃ¼zik Sesi',
      'settings_sfx': 'Efekt Sesi',
      'settings_restore': 'SatÄ±n AlÄ±mlarÄ± Geri YÃ¼kle',
      'settings_restore_sub': 'Elit SÃ¼rÃ¼m lisansÄ±nÄ± kurtarÄ±r.',
      'settings_feedback': 'Geri Bildirim GÃ¶nder',
      'settings_feedback_sub': 'Bize dÃ¼ÅŸÃ¼ncelerinizi iletin.',
      'settings_lang': 'Dil (Language)',
      'day_count': 'GÃœN {day}',
      'logs_title': 'GÃœNLÃœK KAYITLARI',
      'btn_explore': 'KEÅFE Ã‡IK',
      'btn_exploring': 'KEÅÄ°F SÃœRÃœYOR',
      'btn_end_day': 'GÃœNÃœ BÄ°TÄ°R',
      'guide_title': 'NASIL OYNANIR?',
      'guide_text': 'Aileni hayatta tutmak iÃ§in erzaklarÄ± yÃ¶net ve dÄ±ÅŸarÄ±ya keÅŸif ekipleri gÃ¶nder. Su ve yemek olmadan sÄ±ÄŸÄ±nakta hayatta kalamazsÄ±nÄ±z!',
      'guide_close': 'KAPAT',
      'store_title': 'MAÄAZA (GerÃ§ek Para)',
      'store_desc': 'Oyun iÃ§i satÄ±n alÄ±mlar ile destek olabilirsiniz!',
      'store_buy_water': '3 SU AL (0.99\$)',
      'store_buy_soup': '3 Ã‡ORBA AL (0.99\$)',
      'store_close': 'KAPAT',
      'alert_title_failed': 'Ä°ÅLEM Ä°PTAL',
      'alert_purchase_failed': 'SatÄ±n alma iÅŸlemi tamamlanamadÄ± veya iptal edildi.',
      'alert_title_success': 'BAÅARILI',
      'alert_purchase_success': 'SatÄ±n alma baÅŸarÄ±lÄ±! Erzaklar eklendi.',
      'tt_water': 'Su (KiÅŸi baÅŸÄ± 1 adet/gÃ¼n tÃ¼ketilir)',
      'tt_soup': 'Ã‡orba (KiÅŸi baÅŸÄ± 1 adet/gÃ¼n tÃ¼ketilir)',
      'action_water': 'Su Ä°Ã§ir (-1 Su)',
      'action_soup': 'Ã‡orba Yedir (-1 Ã‡orba)',
      'action_medkit': 'Medkit Kullan (-1 Medkit)',
      'action_chat': 'Sohbet Et',
      'role_observer': 'GÃ¶zlemci',
      'btn_close': 'Kapat',
      'guide_s1_desc': 'SÄ±ÄŸÄ±nakta ailenizle birlikte olabildiÄŸince uzun sÃ¼re hayatta kalmak. Su ve Ã‡orba stoklarÄ±nÄ±zÄ± akÄ±llÄ±ca yÃ¶netin. GÃ¼nleri atlatmak iÃ§in saÄŸ alttaki \'GÃ¼nÃ¼ Bitir\' butonunu kullanÄ±n. AÃ§lÄ±k ve susuzluk karakterleri hastalandÄ±rÄ±r, yalnÄ±zlÄ±k delirtir. Herkes Ã¶lÃ¼rse oyun biter.',
      'guide_close_btn': 'AnladÄ±m, Hayatta Kalmaya HazÄ±rÄ±m',
      'log_first_night': 'Ä°lk gece Ã§ok zordu. YukarÄ±dan garip kazÄ±ma sesleri duyduk. Ampul sÃ¼rekli titriyor.',
      'tt_medkit': 'Ä°lk YardÄ±m Kiti (HastalÄ±k veya yaralanmayÄ± iyileÅŸtirir)',
      'tt_tools': 'Alet Ã‡antasÄ± (SÄ±ÄŸÄ±naktaki arÄ±zalarÄ± tamir eder)',
      'tt_ammo': 'MÃ¼himmat (Tehlikelere karÅŸÄ± savunma saÄŸlar)',
      'load_radar': 'Radar AÃ§Ä±lÄ±yor...',
      'load_cache': 'Harita HafÄ±zadan YÃ¼kleniyor...',
      'load_api': 'GerÃ§ek DÃ¼nya Verileri Ã‡ekiliyor (API)...',
      'load_weak': 'Sinyal ZayÄ±f. Tahmini Harita KullanÄ±lÄ±yor...',
      'map_military': 'Askeri Tahliye NoktasÄ±',
      'map_colony': 'Gizli YeraltÄ± Kolonisi (GiriÅŸ iÃ§in 5 Su/5 Ã‡orba)',
      'event_safe': '{char} terk edilmiÅŸ bir dÃ¼kkanda kilitli bir Ã§elik kasa buldu. AÃ§mayÄ± denesin mi?',
      'fail_colony': 'HAYAL KIRIKLIÄI! {char} koloniyi buldu ama iÃ§eri kabul edilmemiz iÃ§in yanÄ±mÄ±zda en az 5 Su ve 5 Ã‡orba gÃ¶tÃ¼rmemiz gerektiÄŸini sÃ¶ylediler. Erzak yetersizliÄŸinden geri Ã§evrildik.',
      'event_depart': '{char}, {dest} bÃ¶lgesine yola Ã§Ä±ktÄ±. UmarÄ±m saÄŸ dÃ¶ner.',
      'event_rescue': 'Ä°nanamÄ±yorum! Kurtarma helikopteri sÄ±ÄŸÄ±naÄŸÄ±n tam Ã¼zerine indi! {char} yolu aÃ§tÄ±. BAÅARDIK, KURTULDUK!',
      'event_win_colony': 'ErzaklarÄ±mÄ±zÄ± sÄ±rtlandÄ±k ve {char} rehberliÄŸinde Gizli YeraltÄ± Kolonisine ulaÅŸtÄ±k. Burada yeni bir hayat baÅŸlÄ±yor. KAZANDINIZ!',
      'res_ambush': 'KÃ–TÃœ HABER! {char}, dÃ¶nÃ¼ÅŸ yolunda yaÄŸmacÄ±larÄ±n pususuna dÃ¼ÅŸtÃ¼. YaralÄ± dÃ¶ndÃ¼!',
      'res_empty': '{char} sÄ±ÄŸÄ±naÄŸa dÃ¶ndÃ¼. GittiÄŸi bÃ¶lge ({dest}) yaÄŸmalanmÄ±ÅŸ, bir ÅŸey bulamadÄ±.',
      'res_pharmacy': 'BAÅARI! {char} eczaneden Ä°lk YardÄ±m Kiti ve Su buldu!',
      'res_market': 'BAÅARI! {char} marketinden {w} su ve {s} Ã§orba getirdi!',
      'res_hardware': 'BAÅARI! {char} nalburdan Alet Ã‡antasÄ± buldu!',
      'res_generic': 'BAÅARI! {char} yanÄ±na {w} su ve {s} Ã§orba getirdi!',
      'evt_herkesldsnakart': 'Herkes Ã¶ldÃ¼... SÄ±ÄŸÄ±nak artÄ±k sessiz bir mezar.',
      'evt_yabancsuyuitive': 'YabancÄ± suyu iÃ§ti ve minnettarlÄ±kla bize kendi kendine yetebilen efsanevi \'Ãœtopya\' kolonisinin koordinatlarÄ±nÄ± verdi! Haritaya eklendi.',
      'evt_yabancminnettar': 'YabancÄ± minnettarlÄ±kla Ã§antasÄ±ndaki son Ä°lk YardÄ±m Kitini bize verdi.',
      'evt_acmaszbirdnyada': 'AcÄ±masÄ±z bir dÃ¼nyadayÄ±z. YabancÄ±yÄ± Ã¶lÃ¼me terk edip yola devam ettik. (Herkesin morali dÃ¼ÅŸtÃ¼)',
      'evt_takasbaarlilkya': 'Takas baÅŸarÄ±lÄ±! Ä°lk YardÄ±m Kiti envantere eklendi.',
      'evt_teklifireddetti': 'Teklifi reddettik. Karakterimiz kendi yoluna gitti.',
      'evt_snaaulatkimdili': 'SÄ±ÄŸÄ±naÄŸa ulaÅŸtÄ±k. Åimdilik gÃ¼vendeyiz. BombanÄ±n sesi kulaklarÄ±mÄ±zÄ± saÄŸÄ±r edecek gibiydi. DÄ±ÅŸarÄ± Ã§Ä±kamayÄ±z.',
      'evt_ilkgeceokzorduy': 'Ä°lk gece Ã§ok zordu. YukarÄ±dan garip tÄ±kÄ±rtÄ±lar duyduk. Ampul sÃ¼rekli gÃ¶z kÄ±rpÄ±yor.',
      'evt_radyodanetbirsi': 'RADYODA NET BÄ°R SÄ°NYAL! \'Hayatta kalanlar, yakÄ±nlardaki Askeri Tahliye NoktasÄ±na gelin. Kurtarma ekipleri hazÄ±r.\' Haritaya eklendi!',
      'evt_radyodanparazit': 'Radyodan parazitli bir ses geliyor... \'Orada kimse var mÄ±? LÃ¼tfen yardÄ±m edin...\' Ses aniden kesildi.',
      'evt_askeribirfrekan': 'Askeri bir frekans yakaladÄ±k! \'SektÃ¶r 4 temiz. Beklemede kalÄ±n.\' Bizim iÃ§in umut olabilir.',
      'evt_sadeceparazitve': 'Sadece parazit ve statik elektrik sesi var. DÄ±ÅŸarÄ±da kimse kalmamÄ±ÅŸ gibi...',
      'evt_garipbirmzikkan': 'Garip bir mÃ¼zik kanalÄ± bulduk. Ã‡alan ÅŸarkÄ± savaÅŸ Ã¶ncesi gÃ¼nleri hatÄ±rlattÄ±. Herkesin morali biraz olsun yerine geldi.',
      'evt_radyoyusadecemz': 'Radyoyu sadece mÃ¼zik dinlemek iÃ§in aÃ§tÄ±k. Klasik mÃ¼zik sÄ±ÄŸÄ±naÄŸÄ±n soÄŸuk duvarlarÄ±nda yankÄ±landÄ±. Moraller dÃ¼zeldi.',
      'evt_dardankapzorlan': 'DÄ±ÅŸarÄ±dan kapÄ± zorlandÄ±! Askerler iÃ§eri girdi. BaÅŸardÄ±k, kurtulduk!',
      'evt_dardanseslergel': 'DÄ±ÅŸarÄ±dan sesler geliyor! KapaÄŸa vuruyorlar. \'Ordu Birlikleri, aÃ§Ä±n!\' Kurtulduk mu?',
      'evt_devasaparlayanm': 'Devasa, parlayan mutant hamambÃ¶cekleri Ã§orba kutularÄ±mÄ±za saldÄ±rÄ±yor!',
      'evt_hepsiniezerekld': 'Hepsini ezerek Ã¶ldÃ¼rdÃ¼k. EÅŸyalarÄ±mÄ±z gÃ¼vende.',
      'evt_bceklerkonserve': 'BÃ¶cekler konserveleri aÃ§amayÄ±p kendi kendilerine gittiler! ÅanslÄ±yÄ±z.',
      'evt_bcekler2orbamzy': 'BÃ¶cekler 2 Ã§orbamÄ±zÄ± yiyip uzaklaÅŸtÄ±...',
      'evt_snanhavalandrma': 'SÄ±ÄŸÄ±naÄŸÄ±n havalandÄ±rmasÄ± bozuldu. Ä°Ã§eriye zehirli hava sÄ±zÄ±yor.',
      'evt_zorolduamatamir': 'Zor oldu ama tamir ettik. CiÄŸerlerimiz bayram etti.',
      'evt_havakalitesiokk': 'Hava kalitesi Ã§ok kÃ¶tÃ¼, herkes hastalandÄ±.',
      'evt_gmgmgecevaktisn': 'GÃœM! GÃœM! Gece vakti sÄ±ÄŸÄ±nak kapaÄŸÄ± yumruklanÄ±yor. Seslerden anladÄ±ÄŸÄ±mÄ±z kadarÄ±yla yaÄŸmacÄ±lar!',
      'evt_havayabirelatee': 'Havaya bir el ateÅŸ ettik. AdÄ±m sesleri koÅŸarak uzaklaÅŸtÄ±.',
      'evt_kapakrpieridald': 'KapaÄŸÄ± kÄ±rÄ±p iÃ§eri daldÄ±lar! ErzaklarÄ±mÄ±zÄ±n bir kÄ±smÄ±nÄ± (2 Su, 2 Ã‡orba) Ã§alÄ±p gittiler.',
      'evt_duvardakieskibo': 'Duvardaki eski borulardan ÅŸiddetli bir tÄ±slama sesi geliyor. SÄ±ÄŸÄ±naÄŸa boÄŸucu bir gaz sÄ±zÄ±yor!',
      'evt_btngecezehirlig': 'BÃ¼tÃ¼n gece zehirli gazÄ± soluyarak borudaki Ã§atlaÄŸÄ± bezlerle tÄ±kamaya Ã§alÄ±ÅŸtÄ±k. SÄ±zÄ±ntÄ± durdu ama Ã§ok yorulduk, birimiz hastalandÄ±.',
      'evt_kedekikutularna': 'KÃ¶ÅŸedeki kutularÄ±n arkasÄ±nda kapaÄŸÄ± ÅŸiÅŸkin ve etiketi silinmiÅŸ iki konserve bulduk. ErzaklarÄ±mÄ±za ekleyelim mi?',
      'evt_konservelerhala': 'Konserveler hala saÄŸlammÄ±ÅŸ! GÄ±damÄ±z arttÄ± (+2 Ã‡orba).',
      'evt_ktfikirdikutula': 'KÃ¶tÃ¼ fikirdi. Kutular delikmiÅŸ, sÄ±zan pis koku birimizi hasta etti.',
      'evt_riskegirmeyedem': 'Riske girmeye deÄŸmez. Ã‡Ã¶pe attÄ±k.',
      'evt_snankaranlveses': 'SÄ±ÄŸÄ±naÄŸÄ±n karanlÄ±k ve sessizliÄŸi yavaÅŸ yavaÅŸ akÄ±l saÄŸlÄ±ÄŸÄ±mÄ±zÄ± etkiliyor. Biri kÃ¶ÅŸede kendi kendine konuÅŸuyor.',
      'evt_eskignlerdengze': 'Eski gÃ¼nlerden, gÃ¼zel anÄ±lardan bahsettik. Zor oldu ama toparlandÄ±k.',
      'btn_aletlezorlaalet': 'Aletle Zorla (Alet)',
      'btn_sessizcebrak': 'Sessizce BÄ±rak',
      'btn_suver1su': 'Su Ver (-1 Su)',
      'btn_grmezdengel': 'GÃ¶rmezden Gel',
      'btn_takasyap2orba': 'Takas Yap (-2 Ã‡orba)',
      'btn_reddet': 'Reddet',
      'btn_kapaa': 'KapaÄŸÄ± AÃ§',
      'btn_aletleez': 'Aletle Ez',
      'btn_saklan': 'Saklan',
      'btn_tamiretalet': 'Tamir Et (Alet)',
      'btn_tamiretme': 'Tamir Etme',
      'btn_silahlakorkutce': 'Silahla Korkut (Cephane)',
      'btn_sessizcebekle': 'Sessizce Bekle',
      'btn_bezlerletka': 'Bezlerle TÄ±ka',
      'btn_stoaekle': 'StoÄŸa Ekle',
      'btn_peat': 'Ã‡Ã¶pe At',
      'btn_uzunuzunsohbete': 'Uzun Uzun Sohbet Et',
      'radio_title': 'AMATÃ–R RADYO K6JFD',
      'radio_desc': 'DÄ±ÅŸ dÃ¼nyadan bir ses duymak veya sadece biraz mÃ¼zik dinlemek, sÄ±ÄŸÄ±naktaki herkesin ruh halini etkileyebilir. GÃ¼nde sadece bir kez kullanabiliriz.',
      'radio_scan': 'Sinyal Tara',
      'radio_scan_sub': 'Askeri veya sivil yayÄ±nlarÄ± ara.',
      'radio_music': 'MÃ¼zik Dinle',
      'radio_music_sub': 'Eski ÅŸarkÄ±lar moralleri yÃ¼kseltir.',
      'store_header': 'KARABORSA / DESTEK',
      'store_header_desc': 'DÄ±ÅŸarÄ±dan veya havadan gelen destek paketleriyle sÄ±ÄŸÄ±naktaki Ã¶mrÃ¼nÃ¼ uzat. Telsizle sipariÅŸ veriyoruz.',
      'store_ad_title': 'Acil Durum Sinyali',
      'store_ad_sub': 'KÄ±sa bir video izle. Ã–dÃ¼l: +1 Su, +1 Ã‡orba.',
      'store_ad_cooldown': 'Sinyal ÅŸarj oluyor. {days} gÃ¼n sonra tekrar kullanÄ±labilir.',
      'store_pack_title': 'Hayatta Kalma Paketi (1\$)',
      'store_pack_sub': '+5 Su, +5 Ã‡orba, +2 Ä°lk YardÄ±m, +2 Cephane.',
      'store_elite_title': 'Elit SÃ¼rÃ¼m (5\$)',
      'store_elite_active': 'Elit SÄ±ÄŸÄ±nak (Aktif)',
      'store_elite_sub': 'Zorunlu reklamlarÄ± kalÄ±cÄ± olarak kaldÄ±r. Bonus: +1 Alet.',
      'store_elite_active_sub': 'Zorunlu reklamlar kaldÄ±rÄ±ldÄ±.',
      'char_Baba': 'Baba',
      'char_Anne': 'Anne',
      'char_Çocuk': 'Çocuk',
      'trait_Tamirci': 'Tamirci',
      'trait_Demir Mide': 'Demir Mide',
      'trait_Koruyucu': 'Koruyucu',
      'trait_İri Yarı': 'İri Yarı',
      'trait_Soğukkanlı': 'Soğukkanlı',
      'trait_Pratik': 'Pratik',
      'trait_Tutumlu': 'Tutumlu',
      'trait_Şifacı': 'Şifacı',
      'trait_Gözlemci': 'Gözlemci',
      'trait_Dirençli': 'Dirençli',
      'trait_Çevik': 'Çevik',
      'trait_Neşeli': 'Neşeli',
      'trait_Ufaklık': 'Ufaklık',
      'trait_Şanslı': 'Şanslı',
      'trait_Gözü Açık': 'Gözü Açık',
      'ui_send_char': 'Gönderilecek Karakter',
      'ui_cancel': 'İptal',
      'ui_confirm': 'Onayla',
      'ui_desc_water': 'Susuzluğunu giderir.',
      'ui_desc_soup': 'Açlığını giderir.',
      'ui_desc_medkit': 'Hastalığı/Yarayı iyileştirir.',
      'ui_desc_chat': 'Moralini yükseltir. (Günde 1 kez)',
      'ui_today_quiet': 'Bugün sakin geçti.',
      'alert_signal_ok': 'SÄ°NYAL ALINDI',
      'alert_signal_ok_msg': 'Destek ulaÅŸtÄ±! +1 Su, +1 Ã‡orba kazanÄ±ldÄ±.',
      'alert_signal_fail': 'SÄ°NYAL KOPTU',
      'alert_signal_fail_msg': 'BaÄŸlantÄ± kurulamadÄ± veya reklam yÃ¼klenemedi. LÃ¼tfen internetinizi kontrol edin.',
      'alert_cargo_ok': 'KARGO ULAÅTI',
      'alert_cargo_ok_msg': 'Paket SatÄ±n AlÄ±ndÄ±! TÃ¼m kaynaklar sÄ±ÄŸÄ±naÄŸa eklendi.',
      'alert_elite_ok': 'ELÄ°T SÃœRÃœM AKTÄ°F',
      'alert_elite_ok_msg': 'Tebrikler! Reklamlar kaldÄ±rÄ±ldÄ± ve +1 Alet eklendi.',
      'guide_header': 'HAYATTA KALMA REHBERÄ°',
      'guide_s1_title': '1. TEMEL AMACINIZ',
      'guide_s2_title': '2. KEÅÄ°F SÄ°STEMÄ° (GERÃ‡EK DÃœNYA HARÄ°TASI)',
      'day_ended': 'GÃœN {day} BÄ°TTÄ°'
    },
    'en': {
      'app_name': 'BUNKER 06',
      'subtitle_tagline': 'How far will you go to survive?',
      'btn_continue': 'CONTINUE',
      'btn_continue_sub': 'Return to the bunker and resume.',
      'btn_new_real': 'NEW GAME: REALISTIC',
      'btn_new_real_sub': 'Maps your exact location.',
      'btn_new_fast': 'NEW GAME: FAST PLAY',
      'btn_new_fast_sub': 'No permissions needed. Uses estimated map.',
      'loading_please_wait': 'Please Wait...',
      'tab_radio': 'RADIO',
      'tab_store': 'STORE',
      'tab_guide': 'GUIDE',
      'settings_title': 'SETTINGS',
      'settings_bgm': 'Music Volume',
      'settings_sfx': 'Effects Volume',
      'settings_restore': 'Restore Purchases',
      'settings_restore_sub': 'Restores Elite Edition license.',
      'settings_feedback': 'Send Feedback',
      'settings_feedback_sub': 'Let us know your thoughts.',
      'settings_lang': 'Language (Dil)',
      'day_count': 'DAY {day}',
      'logs_title': 'DAILY LOGS',
      'btn_explore': 'EXPLORE',
      'btn_exploring': 'EXPLORING',
      'btn_end_day': 'END DAY',
      'guide_title': 'HOW TO PLAY?',
      'guide_text': 'Manage supplies and send out scout teams to keep your family alive. You cannot survive in the bunker without water and food!',
      'guide_close': 'GOT IT',
      'store_title': 'STORE (Real Money)',
      'store_desc': 'Support us with in-game purchases!',
      'store_buy_water': 'GET 3 WATER (0.99\$)',
      'store_buy_soup': 'GET 3 SOUP (0.99\$)',
      'store_close': 'CLOSE',
      'alert_title_failed': 'TRANSACTION CANCELED',
      'alert_purchase_failed': 'Purchase could not be completed or was canceled.',
      'alert_title_success': 'SUCCESS',
      'alert_purchase_success': 'Purchase successful! Supplies added.',
      'tt_water': 'Water (1 consumed per person/day)',
      'tt_soup': 'Soup (1 consumed per person/day)',
      'tt_medkit': 'First Aid Kit (Cures illness or injury)',
      'tt_tools': 'Toolbox (Repairs malfunctions in the bunker)',
      'tt_ammo': 'Ammo (Provides defense against threats)',
      'load_radar': 'Opening Radar...',
      'load_cache': 'Loading Map from Memory...',
      'load_api': 'Fetching Real World Data (API)...',
      'load_weak': 'Weak Signal. Using Estimated Map...',
      'map_military': 'Military Evacuation Point',
      'map_colony': 'Secret Underground Colony (Requires 5 Water/5 Soup)',
      'event_safe': '{char} found a locked steel safe in an abandoned store. Should they try to open it?',
      'fail_colony': 'DISAPPOINTMENT! {char} found the colony, but they said we need to bring at least 5 Water and 5 Soup to be accepted. We were turned away due to lack of supplies.',
      'event_depart': '{char} departed for the {dest} area. Hope they return safely.',
      'event_rescue': 'I can\'t believe it! The rescue helicopter landed right on top of the bunker! {char} cleared the way. WE DID IT, WE ARE SAVED!',
      'event_win_colony': 'We packed our supplies and reached the Secret Underground Colony under {char}\'s guidance. A new life begins here. YOU WIN!',
      'res_ambush': 'BAD NEWS! {char} was ambushed by scavengers on the way back. Returned injured!',
      'res_empty': '{char} returned to the bunker. The {dest} area was already looted, found nothing.',
      'res_pharmacy': 'SUCCESS! {char} found a First Aid Kit and Water at the pharmacy!',
      'res_market': 'SUCCESS! {char} brought back {w} water and {s} soup from the market!',
      'res_hardware': 'SUCCESS! {char} found a Toolbox at the hardware store!',
      'res_generic': 'SUCCESS! {char} brought back {w} water and {s} soup!',
      'evt_herkesldsnakart': 'Everyone died... The bunker is now a silent grave.',
      'evt_yabancsuyuitive': 'The stranger drank the water and gratefully gave us the coordinates of the legendary self-sufficient \'Utopia\' colony! Added to map.',
      'evt_yabancminnettar': 'The stranger gratefully gave us their last First Aid Kit.',
      'evt_acmaszbirdnyada': 'We are in a cruel world. We left the stranger to die and moved on. (Everyone\'s morale dropped)',
      'evt_takasbaarlilkya': 'Trade successful! First Aid Kit added to inventory.',
      'evt_teklifireddetti': 'We declined the offer. Our character went their own way.',
      'evt_snaaulatkimdili': 'We reached the bunker. We are safe for now. The sound of the bomb was deafening. We can\'t go outside.',
      'evt_ilkgeceokzorduy': 'The first night was very hard. We heard strange scratching noises from above. The light bulb keeps flickering.',
      'evt_radyodanetbirsi': 'CLEAR SIGNAL ON RADIO! \'Survivors, head to the nearby Military Evac Point. Rescue teams are ready.\' Added to map!',
      'evt_radyodanparazit': 'Static voice from the radio... \'Is anyone there? Please help...\' The voice suddenly cut off.',
      'evt_askeribirfrekan': 'We caught a military frequency! \'Sector 4 clear. Stand by.\' There might be hope for us.',
      'evt_sadeceparazitve': 'There\'s only static and interference. It\'s as if no one is left outside...',
      'evt_garipbirmzikkan': 'We found a strange music channel. The song playing reminded us of the pre-war days. Everyone\'s morale improved a bit.',
      'evt_radyoyusadecemz': 'We turned on the radio just to listen to music. Classical music echoed in the cold walls of the bunker. Morale improved.',
      'evt_dardankapzorlan': 'The door is being forced from outside! Soldiers burst in. We did it, we are saved!',
      'evt_dardanseslergel': 'There are voices outside! They are banging on the hatch. \'Army Troops, open up!\' Are we saved?',
      'evt_devasaparlayanm': 'Giant, glowing mutant cockroaches are attacking our soup cans!',
      'evt_hepsiniezerekld': 'We crushed and killed them all. Our supplies are safe.',
      'evt_bceklerkonserve': 'The bugs couldn\'t open the cans and left on their own! We\'re lucky.',
      'evt_bcekler2orbamzy': 'The bugs ate 2 of our soups and left...',
      'evt_snanhavalandrma': 'The bunker\'s ventilation broke down. Toxic air is leaking inside.',
      'evt_zorolduamatamir': 'It was hard but we fixed it. Our lungs are rejoicing.',
      'evt_havakalitesiokk': 'Air quality is terrible, everyone got sick.',
      'evt_gmgmgecevaktisn': 'BANG! BANG! Someone is pounding on the bunker hatch at night. From the sounds, they are scavengers!',
      'evt_havayabirelatee': 'We fired a warning shot in the air. The footsteps ran away.',
      'evt_kapakrpieridald': 'They broke the hatch and stormed in! They stole some of our supplies (2 Water, 2 Soup) and left.',
      'evt_duvardakieskibo': 'There\'s a violent hissing sound coming from the old pipes in the wall. Choking gas is leaking into the bunker!',
      'evt_btngecezehirlig': 'We spent all night breathing toxic gas trying to plug the crack with rags. The leak stopped but we are exhausted, one of us got sick.',
      'evt_kedekikutularna': 'We found two unlabelled cans with bulging lids behind the boxes in the corner. Should we add them to our supplies?',
      'evt_konservelerhala': 'The cans are still good! Our food increased (+2 Soup).',
      'evt_ktfikirdikutula': 'Bad idea. The cans were punctured, the foul smell made one of us sick.',
      'evt_riskegirmeyedem': 'Not worth the risk. We threw them away.',
      'evt_snankaranlveses': 'The darkness and silence of the bunker is slowly affecting our sanity. Someone is talking to themselves in the corner.',
      'evt_eskignlerdengze': 'We talked about the old days, good memories. It was hard but we recovered.',
      'btn_aletlezorlaalet': 'Force with Tool (Tool)',
      'btn_sessizcebrak': 'Leave Silently',
      'btn_suver1su': 'Give Water (-1 Water)',
      'btn_grmezdengel': 'Ignore',
      'btn_takasyap2orba': 'Trade (-2 Soup)',
      'btn_reddet': 'Decline',
      'btn_kapaa': 'Open Hatch',
      'btn_aletleez': 'Crush with Tool',
      'btn_saklan': 'Hide',
      'btn_tamiretalet': 'Repair (Tool)',
      'btn_tamiretme': 'Do Not Repair',
      'btn_silahlakorkutce': 'Scare with Gun (Ammo)',
      'btn_sessizcebekle': 'Wait Silently',
      'btn_bezlerletka': 'Plug with Rags',
      'btn_stoaekle': 'Add to Stock',
      'btn_peat': 'Throw Away',
      'btn_uzunuzunsohbete': 'Have a Long Chat',
      'radio_title': 'HAM RADIO K6JFD',
      'radio_desc': 'Hearing a voice from the outside world or just listening to some music can affect everyone\'s mood in the bunker. Can only be used once per day.',
      'radio_scan': 'Scan Signal',
      'radio_scan_sub': 'Search for military or civilian broadcasts.',
      'radio_music': 'Listen to Music',
      'radio_music_sub': 'Old songs boost morale.',
      'store_header': 'BLACK MARKET / SUPPORT',
      'store_header_desc': 'Extend your life in the bunker with supply drops from outside. We\'re ordering via radio.',
      'store_ad_title': 'Emergency Signal',
      'store_ad_sub': 'Watch a short video. Reward: +1 Water, +1 Soup.',
      'store_ad_cooldown': 'Signal recharging. Available again in {days} days.',
      'store_pack_title': 'Survival Pack (1\$)',
      'store_pack_sub': '+5 Water, +5 Soup, +2 First Aid, +2 Ammo.',
      'store_elite_title': 'Elite Edition (5\$)',
      'store_elite_active': 'Elite Bunker (Active)',
      'store_elite_sub': 'Permanently remove forced ads. Bonus: +1 Tool.',
      'store_elite_active_sub': 'Forced ads removed.',
      'char_Baba': 'Dad',
      'char_Anne': 'Mom',
      'char_Çocuk': 'Kid',
      'trait_Tamirci': 'Mechanic',
      'trait_Demir Mide': 'Iron Stomach',
      'trait_Koruyucu': 'Protector',
      'trait_İri Yarı': 'Bulky',
      'trait_Soğukkanlı': 'Calm',
      'trait_Pratik': 'Practical',
      'trait_Tutumlu': 'Frugal',
      'trait_Şifacı': 'Healer',
      'trait_Gözlemci': 'Observer',
      'trait_Dirençli': 'Resilient',
      'trait_Çevik': 'Agile',
      'trait_Neşeli': 'Cheerful',
      'trait_Ufaklık': 'Little One',
      'trait_Şanslı': 'Lucky',
      'trait_Gözü Açık': 'Vigilant',
      'ui_send_char': 'Character to Send',
      'ui_cancel': 'Cancel',
      'ui_confirm': 'Confirm',
      'ui_desc_water': 'Quenches thirst.',
      'ui_desc_soup': 'Sates hunger.',
      'ui_desc_medkit': 'Heals sickness/wound.',
      'ui_desc_chat': 'Improves morale. (Once a day)',
      'ui_today_quiet': 'Today passed quietly.',
      'btn_close': 'Close',
      'alert_signal_ok': 'SIGNAL RECEIVED',
      'alert_signal_ok_msg': 'Supply drop arrived! +1 Water, +1 Soup earned.',
      'alert_signal_fail': 'SIGNAL LOST',
      'alert_signal_fail_msg': 'Connection failed or ad could not load. Please check your internet.',
      'alert_cargo_ok': 'CARGO ARRIVED',
      'alert_cargo_ok_msg': 'Pack purchased! All resources added to the bunker.',
      'alert_elite_ok': 'ELITE EDITION ACTIVE',
      'alert_elite_ok_msg': 'Congratulations! Ads removed and +1 Tool added.',
      'guide_header': 'SURVIVAL GUIDE',
      'guide_s1_title': '1. YOUR MAIN OBJECTIVE',
      'guide_s2_title': '2. EXPLORATION SYSTEM (REAL WORLD MAP)',
      'day_ended': 'DAY {day} ENDED'
    },
  };

  static Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    currentLang = prefs.getString('language') ?? 'tr';
  }

  static Future<void> setLanguage(String lang) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', lang);
    currentLang = lang;
  }

  static String get(String key, [Map<String, String>? vars]) {
    final langDict = _strings[currentLang] ?? _strings['tr']!;
    String text = langDict[key] ?? key;

    if (vars != null) {
      vars.forEach((k, v) {
        text = text.replaceAll('{' + k + '}', v);
      });
    }
    return text;
  }
}

