import 'package:shared_preferences/shared_preferences.dart';

class Loc {
  static String currentLang = 'tr';

  static final Map<String, Map<String, String>> _strings = {
    'tr': {
      'app_name': 'BUNKER 06',
      'subtitle_tagline': 'Hayatta kalmak için ne kadar ileri gidebilirsin?',
      'btn_continue': 'DEVAM ET',
      'btn_continue_sub': 'Sığınağa geri dön ve kaldığın yerden devam et.',
      'btn_new_real': 'YENİ OYUN: GERÇEKÇİ OYNANIŞ',
      'btn_new_real_sub': 'Tam konumunu haritalandırır.',
      'btn_new_fast': 'YENİ OYUN: HIZLI OYNANIŞ',
      'btn_new_fast_sub': 'İzin gerektirmez. Tahmini harita üzerinden ilerler.',
      'loading_please_wait': 'Lütfen Bekleyin...',
      'tab_radio': 'RADYO',
      'tab_store': 'MAĞAZA',
      'tab_guide': 'REHBER',
      'settings_title': 'AYARLAR',
      'settings_bgm': 'Müzik Sesi',
      'settings_sfx': 'Efekt Sesi',
      'settings_restore': 'Satın Alımları Geri Yükle',
      'settings_restore_sub': 'Elit Sürüm lisansını kurtarır.',
      'settings_feedback': 'Geri Bildirim Gönder',
      'settings_feedback_sub': 'Bize düşüncelerinizi iletin.',
      'settings_lang': 'Dil (Language)',
      'day_count': 'GÜN {day}',
      'logs_title': 'GÜNLÜK KAYITLARI',
      'btn_explore': 'KEŞFE ÇIK',
      'btn_exploring': 'KEŞİF SÜRÜYOR',
      'btn_end_day': 'GÜNÜ BİTİR',
      'guide_title': 'NASIL OYNANIR?',
      'guide_text': 'Aileni hayatta tutmak için erzakları yönet ve dışarıya keşif ekipleri gönder. Su ve yemek olmadan sığınakta hayatta kalamazsınız!',
      'guide_close': 'ANLADIM',
      'store_title': 'MAĞAZA (Gerçek Para)',
      'store_desc': 'Oyun içi satın alımlar ile destek olabilirsiniz!',
      'store_buy_water': '3 SU AL (0.99\$)',
      'store_buy_soup': '3 ÇORBA AL (0.99\$)',
      'store_close': 'KAPAT',
      'alert_title_failed': 'İŞLEM İPTAL',
      'alert_purchase_failed': 'Satın alma işlemi tamamlanamadı veya iptal edildi.',
      'alert_title_success': 'BAŞARILI',
      'alert_purchase_success': 'Satın alma başarılı! Erzaklar eklendi.',
      'tt_water': 'Su (Kişi başı 1 adet/gün tüketilir)',
      'tt_soup': 'Çorba (Kişi başı 1 adet/gün tüketilir)',
      'tt_medkit': 'İlk Yardım Kiti (Hastalık veya yaralanmayı iyileştirir)',
      'tt_tools': 'Alet Çantası (Sığınaktaki arızaları tamir eder)',
      'tt_ammo': 'Mühimmat (Tehlikelere karşı savunma sağlar)',
      'load_radar': 'Radar Açılıyor...',
      'load_cache': 'Harita Hafızadan Yükleniyor...',
      'load_api': 'Gerçek Dünya Verileri Çekiliyor (API)...',
      'load_weak': 'Sinyal Zayıf. Tahmini Harita Kullanılıyor...',
      'map_military': 'Askeri Tahliye Noktası',
      'map_colony': 'Gizli Yeraltı Kolonisi (Giriş için 5 Su/5 Çorba)',
      'event_safe': '{char} terk edilmiş bir dükkanda kilitli bir çelik kasa buldu. Açmayı denesin mi?',
      'fail_colony': 'HAYAL KIRIKLIĞI! {char} koloniyi buldu ama içeri kabul edilmemiz için yanımızda en az 5 Su ve 5 Çorba götürmemiz gerektiğini söylediler. Erzak yetersizliğinden geri çevrildik.',
      'event_depart': '{char}, {dest} bölgesine yola çıktı. Umarım sağ döner.',
      'event_rescue': 'İnanamıyorum! Kurtarma helikopteri sığınağın tam üzerine indi! {char} yolu açtı. BAŞARDIK, KURTULDUK!',
      'event_win_colony': 'Erzaklarımızı sırtlandık ve {char} rehberliğinde Gizli Yeraltı Kolonisine ulaştık. Burada yeni bir hayat başlıyor. KAZANDINIZ!',
      'res_ambush': 'KÖTÜ HABER! {char}, dönüş yolunda yağmacıların pususuna düştü. Yaralı döndü!',
      'res_empty': '{char} sığınağa döndü. Gittiği bölge ({dest}) yağmalanmış, bir şey bulamadı.',
      'res_pharmacy': 'BAŞARI! {char} eczaneden İlk Yardım Kiti ve Su buldu!',
      'res_market': 'BAŞARI! {char} marketinden {w} su ve {s} çorba getirdi!',
      'res_hardware': 'BAŞARI! {char} nalburdan Alet Çantası buldu!',
      'res_generic': 'BAŞARI! {char} yanına {w} su ve {s} çorba getirdi!',
      'evt_herkesldsnakart': 'Herkes öldü... Sığınak artık sessiz bir mezar.',
      'evt_yabancsuyuitive': 'Yabancı suyu içti ve minnettarlıkla bize kendi kendine yetebilen efsanevi \'Ütopya\' kolonisinin koordinatlarını verdi! Haritaya eklendi.',
      'evt_yabancminnettar': 'Yabancı minnettarlıkla çantasındaki son İlk Yardım Kitini bize verdi.',
      'evt_acmaszbirdnyada': 'Acımasız bir dünyadayız. Yabancıyı ölüme terk edip yola devam ettik. (Herkesin morali düştü)',
      'evt_takasbaarlilkya': 'Takas başarılı! İlk Yardım Kiti envantere eklendi.',
      'evt_teklifireddetti': 'Teklifi reddettik. Karakterimiz kendi yoluna gitti.',
      'evt_snaaulatkimdili': 'Sığınağa ulaştık. Şimdilik güvendeyiz. Bombanın sesi kulaklarımızı sağır edecek gibiydi. Dışarı çıkamayız.',
      'evt_ilkgeceokzorduy': 'İlk gece çok zordu. Yukarıdan garip tıkırtılar duyduk. Ampul sürekli göz kırpıyor.',
      'evt_radyodanetbirsi': 'RADYODA NET BİR SİNYAL! \'Hayatta kalanlar, yakınlardaki Askeri Tahliye Noktasına gelin. Kurtarma ekipleri hazır.\' Haritaya eklendi!',
      'evt_radyodanparazit': 'Radyodan parazitli bir ses geliyor... \'Orada kimse var mı? Lütfen yardım edin...\' Ses aniden kesildi.',
      'evt_askeribirfrekan': 'Askeri bir frekans yakaladık! \'Sektör 4 temiz. Beklemede kalın.\' Bizim için umut olabilir.',
      'evt_sadeceparazitve': 'Sadece parazit ve statik elektrik sesi var. Dışarıda kimse kalmamış gibi...',
      'evt_garipbirmzikkan': 'Garip bir müzik kanalı bulduk. Çalan şarkı savaş öncesi günleri hatırlattı. Herkesin morali biraz olsun yerine geldi.',
      'evt_radyoyusadecemz': 'Radyoyu sadece müzik dinlemek için açtık. Klasik müzik sığınağın soğuk duvarlarında yankılandı. Moraller düzeldi.',
      'evt_dardankapzorlan': 'Dışarıdan kapı zorlandı! Askerler içeri girdi. Başardık, kurtulduk!',
      'evt_dardanseslergel': 'Dışarıdan sesler geliyor! Kapağa vuruyorlar. \'Ordu Birlikleri, açın!\' Kurtulduk mu?',
      'evt_devasaparlayanm': 'Devasa, parlayan mutant hamamböcekleri çorba kutularımıza saldırıyor!',
      'evt_hepsiniezerekld': 'Hepsini ezerek öldürdük. Eşyalarımız güvende.',
      'evt_bceklerkonserve': 'Böcekler konserveleri açamayıp kendi kendilerine gittiler! Şanslıyız.',
      'evt_bcekler2orbamzy': 'Böcekler 2 çorbamızı yiyip uzaklaştı...',
      'evt_snanhavalandrma': 'Sığınağın havalandırması bozuldu. İçeriye zehirli hava sızıyor.',
      'evt_zorolduamatamir': 'Zor oldu ama tamir ettik. Ciğerlerimiz bayram etti.',
      'evt_havakalitesiokk': 'Hava kalitesi çok kötü, herkes hastalandı.',
      'evt_gmgmgecevaktisn': 'GÜM! GÜM! Gece vakti sığınak kapağı yumruklanıyor. Seslerden anladığımız kadarıyla yağmacılar!',
      'evt_havayabirelatee': 'Havaya bir el ateş ettik. Adım sesleri koşarak uzaklaştı.',
      'evt_kapakrpieridald': 'Kapağı kırıp içeri daldılar! Erzaklarımızın bir kısmını (2 Su, 2 Çorba) çalıp gittiler.',
      'evt_duvardakieskibo': 'Duvardaki eski borulardan şiddetli bir tıslama sesi geliyor. Sığınağa boğucu bir gaz sızıyor!',
      'evt_btngecezehirlig': 'Bütün gece zehirli gazı soluyarak borudaki çatlağı bezlerle tıkamaya çalıştık. Sızıntı durdu ama çok yorulduk, birimiz hastalandı.',
      'evt_kedekikutularna': 'Köşedeki kutuların arkasında kapağı şişkin ve etiketi silinmiş iki konserve bulduk. Erzaklarımıza ekleyelim mi?',
      'evt_konservelerhala': 'Konserveler hala sağlammış! Gıdamız arttı (+2 Çorba).',
      'evt_ktfikirdikutula': 'Kötü fikirdi. Kutular delikmiş, sızan pis koku birimizi hasta etti.',
      'evt_riskegirmeyedem': 'Riske girmeye değmez. Çöpe attık.',
      'evt_snankaranlveses': 'Sığınağın karanlık ve sessizliği yavaş yavaş akıl sağlığımızı etkiliyor. Biri köşede kendi kendine konuşuyor.',
      'evt_eskignlerdengze': 'Eski günlerden, güzel anılardan bahsettik. Zor oldu ama toparlandık.',
      'btn_aletlezorlaalet': 'Aletle Zorla (Alet)',
      'btn_sessizcebrak': 'Sessizce Bırak',
      'btn_suver1su': 'Su Ver (-1 Su)',
      'btn_grmezdengel': 'Görmezden Gel',
      'btn_takasyap2orba': 'Takas Yap (-2 Çorba)',
      'btn_reddet': 'Reddet',
      'btn_kapaa': 'Kapağı Aç',
      'btn_aletleez': 'Aletle Ez',
      'btn_saklan': 'Saklan',
      'btn_tamiretalet': 'Tamir Et (Alet)',
      'btn_tamiretme': 'Tamir Etme',
      'btn_silahlakorkutce': 'Silahla Korkut (Cephane)',
      'btn_sessizcebekle': 'Sessizce Bekle',
      'btn_bezlerletka': 'Bezlerle Tıka',
      'btn_stoaekle': 'Stoğa Ekle',
      'btn_peat': 'Çöpe At',
      'btn_uzunuzunsohbete': 'Uzun Uzun Sohbet Et',
      'radio_title': 'AMATÖR RADYO K6JFD',
      'radio_desc': 'Dış dünyadan bir ses duymak veya sadece biraz müzik dinlemek, sığınaktaki herkesin ruh halini etkileyebilir. Günde sadece bir kez kullanabiliriz.',
      'radio_scan': 'Sinyal Tara',
      'radio_scan_sub': 'Askeri veya sivil yayınları ara.',
      'radio_music': 'Müzik Dinle',
      'radio_music_sub': 'Eski şarkılar moralleri yükseltir.',
      'store_header': 'KARABORSA / DESTEK',
      'store_header_desc': 'Dışarıdan veya havadan gelen destek paketleriyle sığınaktaki ömrünü uzat. Telsizle sipariş veriyoruz.',
      'store_ad_title': 'Acil Durum Sinyali',
      'store_ad_sub': 'Kısa bir video izle. Ödül: +1 Su, +1 Çorba.',
      'store_ad_cooldown': 'Sinyal şarj oluyor. {days} gün sonra tekrar kullanılabilir.',
      'store_pack_title': 'Hayatta Kalma Paketi (1\$)',
      'store_pack_sub': '+5 Su, +5 Çorba, +2 İlk Yardım, +2 Cephane.',
      'store_elite_title': 'Elit Sürüm (5\$)',
      'store_elite_active': 'Elit Sığınak (Aktif)',
      'store_elite_sub': 'Zorunlu reklamları kalıcı olarak kaldır. Bonus: +1 Alet.',
      'store_elite_active_sub': 'Zorunlu reklamlar kaldırıldı.',
      'alert_signal_ok': 'SİNYAL ALINDI',
      'alert_signal_ok_msg': 'Destek ulaştı! +1 Su, +1 Çorba kazanıldı.',
      'alert_signal_fail': 'SİNYAL KOPTU',
      'alert_signal_fail_msg': 'Bağlantı kurulamadı veya reklam yüklenemedi. Lütfen internetinizi kontrol edin.',
      'alert_cargo_ok': 'KARGO ULAŞTI',
      'alert_cargo_ok_msg': 'Paket Satın Alındı! Tüm kaynaklar sığınağa eklendi.',
      'alert_elite_ok': 'ELİT SÜRÜM AKTİF',
      'alert_elite_ok_msg': 'Tebrikler! Reklamlar kaldırıldı ve +1 Alet eklendi.',
      'guide_header': 'HAYATTA KALMA REHBERİ',
      'guide_s1_title': '1. TEMEL AMACINIZ',
      'guide_s2_title': '2. KEŞİF SİSTEMİ (GERÇEK DÜNYA HARİTASI)',
      'day_ended': 'GÜN {day} BİTTİ'
    },
    'en': {
      'app_name': 'BUNKER 06',
      'subtitle_tagline': 'How far will you go to survive?',
      'btn_continue': 'CONTINUE',
      'btn_continue_sub': 'Return to the bunker and resume.',
      'btn_new_real': 'NEW GAME: REALISTIC',
      'btn_new_real_sub': 'Maps your exact location.',
      'btn_new_fast': 'NEW GAME: FAST PLAY',
      'btn_new_fast_sub': 'No permissions needed. Uses estimated map.',
      'loading_please_wait': 'Please Wait...',
      'tab_radio': 'RADIO',
      'tab_store': 'STORE',
      'tab_guide': 'GUIDE',
      'settings_title': 'SETTINGS',
      'settings_bgm': 'Music Volume',
      'settings_sfx': 'Effects Volume',
      'settings_restore': 'Restore Purchases',
      'settings_restore_sub': 'Restores Elite Edition license.',
      'settings_feedback': 'Send Feedback',
      'settings_feedback_sub': 'Let us know your thoughts.',
      'settings_lang': 'Language (Dil)',
      'day_count': 'DAY {day}',
      'logs_title': 'DAILY LOGS',
      'btn_explore': 'EXPLORE',
      'btn_exploring': 'EXPLORING',
      'btn_end_day': 'END DAY',
      'guide_title': 'HOW TO PLAY?',
      'guide_text': 'Manage supplies and send out scout teams to keep your family alive. You cannot survive in the bunker without water and food!',
      'guide_close': 'GOT IT',
      'store_title': 'STORE (Real Money)',
      'store_desc': 'Support us with in-game purchases!',
      'store_buy_water': 'GET 3 WATER (0.99\$)',
      'store_buy_soup': 'GET 3 SOUP (0.99\$)',
      'store_close': 'CLOSE',
      'alert_title_failed': 'TRANSACTION CANCELED',
      'alert_purchase_failed': 'Purchase could not be completed or was canceled.',
      'alert_title_success': 'SUCCESS',
      'alert_purchase_success': 'Purchase successful! Supplies added.',
      'tt_water': 'Water (1 consumed per person/day)',
      'tt_soup': 'Soup (1 consumed per person/day)',
      'tt_medkit': 'First Aid Kit (Cures illness or injury)',
      'tt_tools': 'Toolbox (Repairs malfunctions in the bunker)',
      'tt_ammo': 'Ammo (Provides defense against threats)',
      'load_radar': 'Opening Radar...',
      'load_cache': 'Loading Map from Memory...',
      'load_api': 'Fetching Real World Data (API)...',
      'load_weak': 'Weak Signal. Using Estimated Map...',
      'map_military': 'Military Evacuation Point',
      'map_colony': 'Secret Underground Colony (Requires 5 Water/5 Soup)',
      'event_safe': '{char} found a locked steel safe in an abandoned store. Should they try to open it?',
      'fail_colony': 'DISAPPOINTMENT! {char} found the colony, but they said we need to bring at least 5 Water and 5 Soup to be accepted. We were turned away due to lack of supplies.',
      'event_depart': '{char} departed for the {dest} area. Hope they return safely.',
      'event_rescue': 'I can\'t believe it! The rescue helicopter landed right on top of the bunker! {char} cleared the way. WE DID IT, WE ARE SAVED!',
      'event_win_colony': 'We packed our supplies and reached the Secret Underground Colony under {char}\'s guidance. A new life begins here. YOU WIN!',
      'res_ambush': 'BAD NEWS! {char} was ambushed by scavengers on the way back. Returned injured!',
      'res_empty': '{char} returned to the bunker. The {dest} area was already looted, found nothing.',
      'res_pharmacy': 'SUCCESS! {char} found a First Aid Kit and Water at the pharmacy!',
      'res_market': 'SUCCESS! {char} brought back {w} water and {s} soup from the market!',
      'res_hardware': 'SUCCESS! {char} found a Toolbox at the hardware store!',
      'res_generic': 'SUCCESS! {char} brought back {w} water and {s} soup!',
      'evt_herkesldsnakart': 'Everyone died... The bunker is now a silent grave.',
      'evt_yabancsuyuitive': 'The stranger drank the water and gratefully gave us the coordinates of the legendary self-sufficient \'Utopia\' colony! Added to map.',
      'evt_yabancminnettar': 'The stranger gratefully gave us their last First Aid Kit.',
      'evt_acmaszbirdnyada': 'We are in a cruel world. We left the stranger to die and moved on. (Everyone\'s morale dropped)',
      'evt_takasbaarlilkya': 'Trade successful! First Aid Kit added to inventory.',
      'evt_teklifireddetti': 'We declined the offer. Our character went their own way.',
      'evt_snaaulatkimdili': 'We reached the bunker. We are safe for now. The sound of the bomb was deafening. We can\'t go outside.',
      'evt_ilkgeceokzorduy': 'The first night was very hard. We heard strange scratching noises from above. The light bulb keeps flickering.',
      'evt_radyodanetbirsi': 'CLEAR SIGNAL ON RADIO! \'Survivors, head to the nearby Military Evac Point. Rescue teams are ready.\' Added to map!',
      'evt_radyodanparazit': 'Static voice from the radio... \'Is anyone there? Please help...\' The voice suddenly cut off.',
      'evt_askeribirfrekan': 'We caught a military frequency! \'Sector 4 clear. Stand by.\' There might be hope for us.',
      'evt_sadeceparazitve': 'There\'s only static and interference. It\'s as if no one is left outside...',
      'evt_garipbirmzikkan': 'We found a strange music channel. The song playing reminded us of the pre-war days. Everyone\'s morale improved a bit.',
      'evt_radyoyusadecemz': 'We turned on the radio just to listen to music. Classical music echoed in the cold walls of the bunker. Morale improved.',
      'evt_dardankapzorlan': 'The door is being forced from outside! Soldiers burst in. We did it, we are saved!',
      'evt_dardanseslergel': 'There are voices outside! They are banging on the hatch. \'Army Troops, open up!\' Are we saved?',
      'evt_devasaparlayanm': 'Giant, glowing mutant cockroaches are attacking our soup cans!',
      'evt_hepsiniezerekld': 'We crushed and killed them all. Our supplies are safe.',
      'evt_bceklerkonserve': 'The bugs couldn\'t open the cans and left on their own! We\'re lucky.',
      'evt_bcekler2orbamzy': 'The bugs ate 2 of our soups and left...',
      'evt_snanhavalandrma': 'The bunker\'s ventilation broke down. Toxic air is leaking inside.',
      'evt_zorolduamatamir': 'It was hard but we fixed it. Our lungs are rejoicing.',
      'evt_havakalitesiokk': 'Air quality is terrible, everyone got sick.',
      'evt_gmgmgecevaktisn': 'BANG! BANG! Someone is pounding on the bunker hatch at night. From the sounds, they are scavengers!',
      'evt_havayabirelatee': 'We fired a warning shot in the air. The footsteps ran away.',
      'evt_kapakrpieridald': 'They broke the hatch and stormed in! They stole some of our supplies (2 Water, 2 Soup) and left.',
      'evt_duvardakieskibo': 'There\'s a violent hissing sound coming from the old pipes in the wall. Choking gas is leaking into the bunker!',
      'evt_btngecezehirlig': 'We spent all night breathing toxic gas trying to plug the crack with rags. The leak stopped but we are exhausted, one of us got sick.',
      'evt_kedekikutularna': 'We found two unlabelled cans with bulging lids behind the boxes in the corner. Should we add them to our supplies?',
      'evt_konservelerhala': 'The cans are still good! Our food increased (+2 Soup).',
      'evt_ktfikirdikutula': 'Bad idea. The cans were punctured, the foul smell made one of us sick.',
      'evt_riskegirmeyedem': 'Not worth the risk. We threw them away.',
      'evt_snankaranlveses': 'The darkness and silence of the bunker is slowly affecting our sanity. Someone is talking to themselves in the corner.',
      'evt_eskignlerdengze': 'We talked about the old days, good memories. It was hard but we recovered.',
      'btn_aletlezorlaalet': 'Force with Tool (Tool)',
      'btn_sessizcebrak': 'Leave Silently',
      'btn_suver1su': 'Give Water (-1 Water)',
      'btn_grmezdengel': 'Ignore',
      'btn_takasyap2orba': 'Trade (-2 Soup)',
      'btn_reddet': 'Decline',
      'btn_kapaa': 'Open Hatch',
      'btn_aletleez': 'Crush with Tool',
      'btn_saklan': 'Hide',
      'btn_tamiretalet': 'Repair (Tool)',
      'btn_tamiretme': 'Do Not Repair',
      'btn_silahlakorkutce': 'Scare with Gun (Ammo)',
      'btn_sessizcebekle': 'Wait Silently',
      'btn_bezlerletka': 'Plug with Rags',
      'btn_stoaekle': 'Add to Stock',
      'btn_peat': 'Throw Away',
      'btn_uzunuzunsohbete': 'Have a Long Chat',
      'radio_title': 'HAM RADIO K6JFD',
      'radio_desc': 'Hearing a voice from the outside world or just listening to some music can affect everyone\'s mood in the bunker. Can only be used once per day.',
      'radio_scan': 'Scan Signal',
      'radio_scan_sub': 'Search for military or civilian broadcasts.',
      'radio_music': 'Listen to Music',
      'radio_music_sub': 'Old songs boost morale.',
      'store_header': 'BLACK MARKET / SUPPORT',
      'store_header_desc': 'Extend your life in the bunker with supply drops from outside. We\'re ordering via radio.',
      'store_ad_title': 'Emergency Signal',
      'store_ad_sub': 'Watch a short video. Reward: +1 Water, +1 Soup.',
      'store_ad_cooldown': 'Signal recharging. Available again in {days} days.',
      'store_pack_title': 'Survival Pack (1\$)',
      'store_pack_sub': '+5 Water, +5 Soup, +2 First Aid, +2 Ammo.',
      'store_elite_title': 'Elite Edition (5\$)',
      'store_elite_active': 'Elite Bunker (Active)',
      'store_elite_sub': 'Permanently remove forced ads. Bonus: +1 Tool.',
      'store_elite_active_sub': 'Forced ads removed.',
      'alert_signal_ok': 'SIGNAL RECEIVED',
      'alert_signal_ok_msg': 'Supply drop arrived! +1 Water, +1 Soup earned.',
      'alert_signal_fail': 'SIGNAL LOST',
      'alert_signal_fail_msg': 'Connection failed or ad could not load. Please check your internet.',
      'alert_cargo_ok': 'CARGO ARRIVED',
      'alert_cargo_ok_msg': 'Pack purchased! All resources added to the bunker.',
      'alert_elite_ok': 'ELITE EDITION ACTIVE',
      'alert_elite_ok_msg': 'Congratulations! Ads removed and +1 Tool added.',
      'guide_header': 'SURVIVAL GUIDE',
      'guide_s1_title': '1. YOUR MAIN OBJECTIVE',
      'guide_s2_title': '2. EXPLORATION SYSTEM (REAL WORLD MAP)',
      'day_ended': 'DAY {day} ENDED'
    },
  };

  static Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    currentLang = prefs.getString('language') ?? 'tr';
  }

  static Future<void> setLanguage(String lang) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', lang);
    currentLang = lang;
  }

  static String get(String key, [Map<String, String>? vars]) {
    final langDict = _strings[currentLang] ?? _strings['tr']!;
    String text = langDict[key] ?? key;

    if (vars != null) {
      vars.forEach((k, v) {
        text = text.replaceAll('{' + k + '}', v);
      });
    }
    return text;
  }
}
