with open(r'c:\Projeler\bunker_60\lib\localization.dart', 'r', encoding='utf-8') as f:
    content = f.read()

tr_ui = """      'event_all_dead': 'Herkes öldü... Sığınak artık sessiz bir mezar.',
      'event_char_outside': '{desc}\\n\\n{char} hala dışarıda, dönmesini bekliyoruz.',
      'event_radio_safe': "TELSİZ: {char} terk edilmiş bir dükkanda kilitli bir çelik kasa buldu. Açmayı denesin mi?",
      'action_force_tool': 'Aletle Zorla (Alet)',
      'event_safe_opened': 'Kasa açıldı! İçinden 2 Su ve 2 Çorba çıktı. {char} yola devam ediyor.',
      'action_leave_silently': 'Sessizce Bırak',
      'event_safe_left': 'Riski göze almadık. {char} sessizce keşfe devam ediyor.',
      'event_radio_stranger': "TELSİZ: {char} yolda yaralı, çaresiz bir yabancıya rastladı. Telsizden 'Ona yardım edeyim mi?' diye soruyor.",
      'action_give_water': 'Su Ver (-1 Su)',
      'event_stranger_utopia': "Yabancı suyu içti ve minnettarlıkla bize kendi kendine yetebilen efsanevi 'Ütopya' kolonisinin koordinatlarını verdi! Haritaya eklendi.",
      'event_stranger_medkit': 'Yabancı minnettarlıkla çantasındaki son İlk Yardım Kitini bize verdi.',
      'action_ignore': 'Görmezden Gel',
      'event_stranger_ignored': 'Acımasız bir dünyadayız. Yabancıyı ölüme terk edip yola devam ettik. (Herkesin morali düştü)',
      'event_radio_trader': 'TELSİZ: {char} dost canlısı görünen bir hayatta kalanla karşılaştı. 2 Çorba karşılığında 1 İlk Yardım Kiti takası teklif ediyor.',
      'action_trade': 'Takas Yap (-2 Çorba)',
      'event_trade_success': 'Takas başarılı! İlk Yardım Kiti envantere eklendi.',
      'event_trade_rejected': 'Teklifi reddettik. Karakterimiz kendi yoluna gitti.',
      'log_first_day': 'Sığınağa ulaştık. Şimdilik güvendeyiz. Bombanın sesi kulaklarımızı sağır edecek gibiydi. Dışarı çıkamayız.',
      'log_first_night': 'İlk gece çok zordu. Yukarıdan garip tıkırtılar duyduk. Ampul sürekli göz kırpıyor.',
      'radio_military_found': "RADYODA NET BİR SİNYAL! 'Hayatta kalanlar, yakınlardaki Askeri Tahliye Noktasına gelin. Kurtarma ekipleri hazır.' Haritaya eklendi!",
      'radio_signal_lost': "Radyodan parazitli bir ses geliyor... 'Orada kimse var mı? Lütfen yardım edin...' Ses aniden kesildi.",
      'radio_military_hope': "Askeri bir frekans yakaladık! 'Sektör 4 temiz. Beklemede kalın.' Bizim için umut olabilir.",
      'radio_static': 'Sadece parazit ve statik elektrik sesi var. Dışarıda kimse kalmamış gibi...',
      'radio_music_good': 'Garip bir müzik kanalı bulduk. Çalan şarkı savaş öncesi günleri hatırlattı. Herkesin morali biraz olsun yerine geldi.',
      'radio_music_classic': 'Radyoyu sadece müzik dinlemek için açtık. Klasik müzik sığınağın soğuk duvarlarında yankılandı. Moraller düzeldi.',
      'ending_army': 'Dışarıdan kapı zorlandı! Askerler içeri girdi. Başardık, kurtulduk!',
      'action_crush_tool': 'Aletle Ez',
      'action_fix_tool': 'Tamir Et (Alet)',
      'action_dont_fix': 'Tamir Etme',
      'action_scare_gun': 'Silahla Korkut (Cephane)',
      'action_wait_silently': 'Sessizce Bekle',
      'action_chat_long': 'Uzun Uzun Sohbet Et',
      'gps_location': 'GPS Konumu',
      'ip_error': 'IP Hata: {e}',
      'ui_use_medkit': 'Medkit Kullan (-1 Medkit)',
      'ui_chat': 'Sohbet Et',
      'ui_target_not_found': 'HEDEF BULUNAMADI',
      'ui_scan_signal_btn': 'Sinyal Tara',
      'ui_black_market': 'KARABORSA / DESTEK',
      'ui_emergency_signal': 'Acil Durum Sinyali',
      'ui_survival_pack': 'Hayatta Kalma Paketi (\\$1)',
"""

en_ui = """      'event_all_dead': 'Everyone died... The bunker is now a silent tomb.',
      'event_char_outside': '{desc}\\n\\n{char} is still outside, we are waiting for their return.',
      'event_radio_safe': "RADIO: {char} found a locked steel safe in an abandoned shop. Should they try to open it?",
      'action_force_tool': 'Force with Tool (Tool)',
      'event_safe_opened': 'Safe opened! Found 2 Water and 2 Soup. {char} continues on.',
      'action_leave_silently': 'Leave Silently',
      'event_safe_left': 'We did not take the risk. {char} quietly continues exploring.',
      'event_radio_stranger': "RADIO: {char} came across an injured, helpless stranger on the road. Asking 'Should I help them?' over the radio.",
      'action_give_water': 'Give Water (-1 Water)',
      'event_stranger_utopia': "The stranger drank the water and gratefully gave us the coordinates of the self-sufficient legendary 'Utopia' colony! Added to map.",
      'event_stranger_medkit': 'The stranger gratefully gave us the last Medkit in their bag.',
      'action_ignore': 'Ignore',
      'event_stranger_ignored': 'We are in a cruel world. We left the stranger to die and moved on. (Everyone\\'s morale dropped)',
      'event_radio_trader': 'RADIO: {char} encountered a friendly-looking survivor. They offer to trade 1 Medkit for 2 Soups.',
      'action_trade': 'Trade (-2 Soup)',
      'event_trade_success': 'Trade successful! Medkit added to inventory.',
      'event_trade_rejected': 'We rejected the offer. Our character went their own way.',
      'log_first_day': 'We reached the bunker. Safe for now. The sound of the bomb was deafening. We cannot go outside.',
      'log_first_night': 'The first night was very hard. Heard strange clicking sounds from above. The light bulb keeps flickering.',
      'radio_military_found': "CLEAR SIGNAL ON RADIO! 'Survivors, proceed to the nearby Military Evacuation Point. Rescue teams are ready.' Added to map!",
      'radio_signal_lost': "Static voice on the radio... 'Is anyone there? Please help...' The signal suddenly cut off.",
      'radio_military_hope': "Caught a military frequency! 'Sector 4 clear. Stand by.' There might be hope for us.",
      'radio_static': 'Only static and white noise. It feels like no one is left out there...',
      'radio_music_good': 'Found a strange music channel. The song playing reminded us of pre-war days. Everyone\\'s morale recovered slightly.',
      'radio_music_classic': 'We turned on the radio just to listen to music. Classical music echoed on the cold walls of the bunker. Morale improved.',
      'ending_army': 'The door was forced from the outside! Soldiers breached in. We did it, we are saved!',
      'action_crush_tool': 'Crush with Tool',
      'action_fix_tool': 'Fix (Tool)',
      'action_dont_fix': 'Do Not Fix',
      'action_scare_gun': 'Scare with Gun (Ammo)',
      'action_wait_silently': 'Wait Silently',
      'action_chat_long': 'Have a Long Chat',
      'gps_location': 'GPS Location',
      'ip_error': 'IP Error: {e}',
      'ui_use_medkit': 'Use Medkit (-1 Medkit)',
      'ui_chat': 'Chat',
      'ui_target_not_found': 'TARGET NOT FOUND',
      'ui_scan_signal_btn': 'Scan Signal',
      'ui_black_market': 'BLACK MARKET / SUPPORT',
      'ui_emergency_signal': 'Emergency Signal',
      'ui_survival_pack': 'Survival Pack (\\$1)',
"""

content = content.replace("'unknown_region': \"Bilinmeyen Bölge\",\n", "'unknown_region': \"Bilinmeyen Bölge\",\n" + tr_ui, 1)
content = content.replace("'unknown_region': \"Unknown Region\",\n", "'unknown_region': \"Unknown Region\",\n" + en_ui, 1)

with open(r'c:\Projeler\bunker_60\lib\localization.dart', 'w', encoding='utf-8') as f:
    f.write(content)
