with open(r'c:\Projeler\bunker_60\lib\localization.dart', 'r', encoding='utf-8') as f:
    content = f.read()

tr_ui = """      'ui_success': 'BAŞARILI',
      'ui_restore_success': 'Satın alımlarınız başarıyla geri yüklendi! Reklamlar kaldırıldı.',
      'ui_info': 'BİLGİ',
      'ui_restore_fail': 'Geri yüklenecek aktif bir satın alım bulunamadı.',
      'ui_conn_error': 'BAĞLANTI HATASI',
      'ui_conn_error_desc': 'Sunucuyla iletişim kurulamadı. İnternetinizi kontrol edin.',
      'ui_signal_lost': 'SİNYAL KESİLDİ',
      'ui_days_survived': 'HAYATTA KALINAN GÜN',
      'ui_back_to_menu': 'ANA MENÜYE DÖN',
      'ui_bunker_days': 'SIĞINAKTA GEÇEN GÜN',
      'ui_give_water': 'Su İçir (-1 Su)',
      'ui_give_water_desc': 'Susuzluğunu giderir.',
      'ui_give_soup': 'Çorba Yedir (-1 Çorba)',
      'ui_give_soup_desc': 'Açlığını giderir.',
      'ui_give_medkit_desc': 'Hastalığı/Yarayı iyileştirir.',
      'ui_chat_desc': 'Moralini yükseltir. (Günde 1 kez)',
      'ui_day_counter': 'GÜN {day}',
      'ui_soup': 'Çorba',
      'ui_medkit': 'İlk Yardım Kiti',
      'ui_tool': 'Alet Çantası',
      'ui_store': 'MAĞAZA',
      'ui_logs': 'GÜNLÜK KAYITLARI',
      'ui_expedition_ongoing': 'KEŞİF SÜRÜYOR',
      'ui_expedition_start': 'KEŞFE ÇIK',
      'ui_end_day': 'GÜNÜ BİTİR',
      'ui_plan_expedition': 'Keşif Görevi Planla',
      'ui_select_target': 'Hedef Seçimi',
      'ui_select_char': 'Gönderilecek Karakter',
      'ui_cancel': 'İptal',
      'ui_please_select_target': 'Lütfen haritadan göndermek istediğiniz mekanı seçin.',
      'ui_radio_title': 'AMATÖR RADYO K6JFD',
      'ui_radio_desc': 'Dış dünyadan bir ses duymak veya sadece biraz müzik dinlemek, sığınaktaki herkesin ruh halini etkileyebilir. Günde sadece bir kez kullanabiliriz.',
      'ui_scan_signal': 'Askeri veya sivil yayınları ara.',
      'ui_listen_music': 'Müzik Dinle',
      'ui_listen_music_desc': 'Eski şarkılar moralleri yükseltir.',
      'ui_store_desc': 'Dışarıdan veya havadan gelen destek paketleriyle sığınaktaki ömrünü uzat. Telsizle sipariş veriyoruz.',
      'ui_watch_ad_desc': 'Kısa bir video izle. Ödül: +1 Su, +1 Çorba.',
      'ui_ad_cooldown': 'Sinyal şarj oluyor. {days} gün sonra tekrar kullanılabilir.',
      'ui_signal_received': 'SİNYAL ALINDI',
      'ui_ad_reward': 'Destek ulaştı! +1 Su, +1 Çorba kazanıldı.',
      'ui_ad_fail': 'Bağlantı kurulamadı veya reklam yüklenemedi. Lütfen internetinizi kontrol edin.',
      'ui_buy_pack_desc': '+5 Su, +5 Çorba, +2 İlk Yardım, +2 Cephane.',
      'ui_cargo_arrived': 'KARGO ULAŞTI',
      'ui_pack_bought': 'Paket Satın Alındı! Tüm kaynaklar sığınağa eklendi.',
      'ui_transaction_cancel': 'İŞLEM İPTAL',
      'ui_transaction_cancel_desc': 'Satın alma işlemi tamamlanamadı veya iptal edildi.',
      'ui_elite_active': 'Elit Sığınak (Aktif)',
      'ui_elite_buy': 'Elit Sürüm (\\$5)',
      'ui_elite_desc_active': 'Zorunlu reklamlar kaldırıldı.',
      'ui_elite_desc_buy': 'Zorunlu reklamları kalıcı olarak kaldır. Bonus: +1 Alet.',
      'ui_elite_success': 'ELİT SÜRÜM AKTİF',
      'ui_elite_success_desc': 'Tebrikler! Reklamlar kaldırıldı ve +1 Alet eklendi.',
      'ui_guide_title': 'HAYATTA KALMA REHBERİ',
      'ui_guide_1': '1. TEMEL AMACINIZ',
      'ui_guide_1_desc': 'Sığınakta ailenizle birlikte olabildiğince uzun süre hayatta kalmak. Su ve çorba stoklarınızı akıllıca yönetin. Günleri atlatmak için sağ alttaki \\'Günü Bitir\\' butonunu kullanın. Açlık ve susuzluk karakterleri hastalandırır, yalnızlık delirtir. Herkes ölürse oyun biter.',
      'ui_guide_2': '2. KEŞİF SİSTEMİ (GERÇEK DÜNYA HARİTASI)',
      'ui_guide_2_desc': 'Oyun, cihazınızın konumunu kullanarak etrafınızdaki gerçek dünyayı haritalandırır. \\'Keşfe Çık\\' diyerek karakterlerinizi Eczane, Market veya Nalbur gibi yakınınızdaki noktalara erzak toplamaya gönderebilirsiniz. Dışarıdaki tehlikeli olaylara ve yağmacılara karşı dikkatli olun!',
      'ui_guide_3': '3. KARAKTER YETENEK (TRAIT) SİSTEMİ',
      'ui_guide_3_desc': 'Ailenin her üyesi oyuna tamamen rastgele yeteneklerle (örn: Demir Mide, Şifacı, Çevik) başlar. Karakterlerinizin portresine tıklayarak durumlarını görün, yemek/su verin, medkit kullanın veya sohbet ederek morallerini yüksek tutun.',
      'ui_guide_4': '4. KAYNAK VE ENVANTER YÖNETİMİ',
      'ui_guide_4_desc': '• Su & Çorba: Temel yaşam kaynağıdır.\\n• İlk Yardım Kiti (Medkit): Hastalık ve yaralanmaları anında iyileştirir.\\n• Alet Çantası (Tool): Havalandırma gibi sığınak arızalarını tamir etmenizi veya keşiflerdeki kilitli kasaları açmanızı sağlar.\\n• Cephane: Gece sığınağa saldıran yağmacıları veya yaratıkları savuşturmak için şarttır.',
      'ui_guide_5': '5. RADYO VE GİZLİ SONLAR',
      'ui_guide_5_desc': 'Kurtuluş için tek yol sığınakta çürümek değil! Günde bir kez radyoyu kullanarak askeri frekansları arayabilir (Sinyal Tara) veya müzik dinleyerek moralleri düzeltebilirsiniz. Askeri tahliye noktalarını bularak veya gizemli \\'Ütopya\\' kolonisine giden yolu açarak ailenizi kurtarın.',
      'ui_guide_ready': 'Anladım, Hayatta Kalmaya Hazırım',
      'ui_settings': 'AYARLAR',
      'ui_music_vol': 'Müzik Sesi',
      'ui_sfx_vol': 'Efekt Sesi',
      'ui_restore_purchases': 'Satın Alımları Geri Yükle',
      'ui_restore_desc': 'Elit Sürüm lisansını kurtarır.',
      'ui_send_feedback': 'Geri Bildirim Gönder',
      'ui_feedback_desc': 'Bize düşüncelerinizi iletin.',
      'ui_day_ended': 'GÜN {day} BİTTİ',
"""

en_ui = """      'ui_success': 'SUCCESS',
      'ui_restore_success': 'Purchases restored successfully! Ads removed.',
      'ui_info': 'INFO',
      'ui_restore_fail': 'No active purchase found to restore.',
      'ui_conn_error': 'CONNECTION ERROR',
      'ui_conn_error_desc': 'Could not connect to the server. Check your internet.',
      'ui_signal_lost': 'SIGNAL LOST',
      'ui_days_survived': 'DAYS SURVIVED',
      'ui_back_to_menu': 'BACK TO MENU',
      'ui_bunker_days': 'DAYS IN BUNKER',
      'ui_give_water': 'Give Water (-1 Water)',
      'ui_give_water_desc': 'Quenches thirst.',
      'ui_give_soup': 'Give Soup (-1 Soup)',
      'ui_give_soup_desc': 'Satisfies hunger.',
      'ui_give_medkit_desc': 'Heals sickness/injury.',
      'ui_chat_desc': 'Boosts morale. (Once a day)',
      'ui_day_counter': 'DAY {day}',
      'ui_soup': 'Soup',
      'ui_medkit': 'Medkit',
      'ui_tool': 'Tool',
      'ui_store': 'STORE',
      'ui_logs': 'LOGS',
      'ui_expedition_ongoing': 'ON EXPEDITION',
      'ui_expedition_start': 'EXPEDITION',
      'ui_end_day': 'END DAY',
      'ui_plan_expedition': 'Plan Expedition',
      'ui_select_target': 'Select Target',
      'ui_select_char': 'Select Character',
      'ui_cancel': 'Cancel',
      'ui_please_select_target': 'Please select a location from the map to explore.',
      'ui_radio_title': 'AMATEUR RADIO K6JFD',
      'ui_radio_desc': 'Hearing a voice from the outside world or just listening to some music can affect everyone\\'s mood in the bunker. We can only use it once a day.',
      'ui_scan_signal': 'Scan for military or civilian broadcasts.',
      'ui_listen_music': 'Listen to Music',
      'ui_listen_music_desc': 'Old songs boost morale.',
      'ui_store_desc': 'Extend your life in the bunker with supply drops from the outside or air. We order via radio.',
      'ui_watch_ad_desc': 'Watch a short video. Reward: +1 Water, +1 Soup.',
      'ui_ad_cooldown': 'Signal charging. Available in {days} days.',
      'ui_signal_received': 'SIGNAL RECEIVED',
      'ui_ad_reward': 'Supplies arrived! +1 Water, +1 Soup gained.',
      'ui_ad_fail': 'Could not connect or load ad. Please check your internet.',
      'ui_buy_pack_desc': '+5 Water, +5 Soup, +2 Medkits, +2 Ammo.',
      'ui_cargo_arrived': 'CARGO ARRIVED',
      'ui_pack_bought': 'Package Bought! All resources added to bunker.',
      'ui_transaction_cancel': 'TRANSACTION CANCELLED',
      'ui_transaction_cancel_desc': 'The purchase could not be completed or was cancelled.',
      'ui_elite_active': 'Elite Bunker (Active)',
      'ui_elite_buy': 'Elite Edition (\\$5)',
      'ui_elite_desc_active': 'Forced ads removed.',
      'ui_elite_desc_buy': 'Permanently remove forced ads. Bonus: +1 Tool.',
      'ui_elite_success': 'ELITE EDITION ACTIVE',
      'ui_elite_success_desc': 'Congratulations! Ads removed and +1 Tool added.',
      'ui_guide_title': 'SURVIVAL GUIDE',
      'ui_guide_1': '1. YOUR MAIN GOAL',
      'ui_guide_1_desc': 'Survive as long as possible with your family in the bunker. Manage your water and soup stocks wisely. Use the \\'End Day\\' button on the bottom right to pass days. Hunger and thirst make characters sick, loneliness drives them mad. If everyone dies, the game is over.',
      'ui_guide_2': '2. EXPEDITION SYSTEM (REAL WORLD MAP)',
      'ui_guide_2_desc': 'The game maps the real world around you using your device\\'s location. By clicking \\'Expedition\\', you can send your characters to nearby spots like Pharmacy, Market, or Hardware store to gather supplies. Beware of dangerous events and raiders outside!',
      'ui_guide_3': '3. CHARACTER TRAIT SYSTEM',
      'ui_guide_3_desc': 'Every family member starts the game with completely random traits (e.g. Iron Stomach, Healer, Agile). Click on their portrait to see their status, give them food/water, use medkits, or chat to keep their morale high.',
      'ui_guide_4': '4. RESOURCE AND INVENTORY MANAGEMENT',
      'ui_guide_4_desc': '• Water & Soup: Basic life source.\\n• Medkit: Instantly heals sickness and injuries.\\n• Tool: Allows you to fix bunker breakdowns like ventilation or open locked safes on expeditions.\\n• Ammo: Essential for fending off raiders or creatures attacking the bunker at night.',
      'ui_guide_5': '5. RADIO AND SECRET ENDINGS',
      'ui_guide_5_desc': 'Rotting in the bunker isn\\'t the only way out! Use the radio once a day to scan for military frequencies or listen to music to fix morale. Save your family by finding military evacuation points or opening the way to the mysterious \\'Utopia\\' colony.',
      'ui_guide_ready': 'Understood, I am ready to survive',
      'ui_settings': 'SETTINGS',
      'ui_music_vol': 'Music Volume',
      'ui_sfx_vol': 'SFX Volume',
      'ui_restore_purchases': 'Restore Purchases',
      'ui_restore_desc': 'Restores Elite Edition license.',
      'ui_send_feedback': 'Send Feedback',
      'ui_feedback_desc': 'Let us know your thoughts.',
      'ui_day_ended': 'DAY {day} ENDED',
"""

content = content.replace("'unknown_region': \"Bilinmeyen Bölge\",\n    },\n    'en': {", "'unknown_region': \"Bilinmeyen Bölge\",\n" + tr_ui + "    },\n    'en': {", 1)
content = content.replace("'unknown_region': \"Unknown Region\",\n    }", "'unknown_region': \"Unknown Region\",\n" + en_ui + "    }", 1)

with open(r'c:\Projeler\bunker_60\lib\localization.dart', 'w', encoding='utf-8') as f:
    f.write(content)
