with open(r'c:\Projeler\bunker_60\lib\localization.dart', 'r', encoding='utf-8') as f:
    loc_content = f.read()

tr_events = '''      'event_army_fake': "Dışarıdan sesler geliyor! Kapağa vuruyorlar. 'Ordu Birlikleri, açın!' Kurtulduk mu?",
      'action_open_hatch': "Kapağı Aç",
      'event_roaches': "Devasa, parlayan mutant hamamböcekleri çorba kutularımıza saldırıyor!",
      'event_roaches_killed': "Hepsini ezerek öldürdük. Eşyalarımız güvende.",
      'event_roaches_left': "Böcekler konserveleri açamayıp kendi kendilerine gittiler! Şanslıyız.",
      'event_roaches_stole': "Böcekler 2 çorbamızı yiyip uzaklaştı...",
      'event_vent_broken': "Sığınağın havalandırması bozuldu. İçeriye zehirli hava sızıyor.",
      'event_vent_fixed': "Zor oldu ama tamir ettik. Ciğerlerimiz bayram etti.",
      'event_vent_sick': "Hava kalitesi çok kötü, herkes hastalandı.",
      'event_raiders': "GÜM! GÜM! Gece vakti sığınak kapağı yumruklanıyor. Seslerden anladığımız kadarıyla yağmacılar!",
      'event_raiders_scared': "Havaya bir el ateş ettik. Adım sesleri koşarak uzaklaştı.",
      'event_raiders_stole': "Kapağı kırıp içeri daldılar! Erzaklarımızın bir kısmını (2 Su, 2 Çorba) çalıp gittiler.",
      'event_gas_leak': "Duvardaki eski borulardan şiddetli bir tıslama sesi geliyor. Sığınağa boğucu bir gaz sızıyor!",
      'action_plug_rags': "Bezlerle Tıka",
      'event_gas_tired': "Bütün gece zehirli gazı soluyarak borudaki çatlağı bezlerle tıkamaya çalıştık. Sızıntı durdu ama çok yorulduk, birimiz hastalandı.",
      'event_sus_cans': "Köşedeki kutuların arkasında kapağı şişkin ve etiketi silinmiş iki konserve bulduk. Erzaklarımıza ekleyelim mi?",
      'action_add_stock': "Stoğa Ekle",
      'event_cans_good': "Konserveler hala sağlammış! Gıdamız arttı (+2 Çorba).",
      'event_cans_bad': "Kötü fikirdi. Kutular delikmiş, sızan pis koku birimizi hasta etti.",
      'action_throw_away': "Çöpe At",
      'event_cans_thrown': "Riske girmeye değmez. Çöpe attık.",
      'event_madness': "Sığınağın karanlığı ve sessizliği yavaş yavaş akıl sağlığımızı etkiliyor. Biri köşede kendi kendine konuşuyor.",
      'event_madness_cured': "Eski günlerden, güzel anılardan bahsettik. Zor oldu ama toparlandık.",
      'log_quiet_day': "{day}. Gün. Sığınakta sessiz bir bekleyiş sürüyor. Kaynakları idareli kullanmalıyız.",
      'log_expedition_start': "{char}, {dest} bölgesine yola çıktı. Umarım sağ döner.",
      'ending_heli': "İnanamıyorum! Kurtarma helikopteri sığınağın tam üzerine indi! {char} yolu açtı. BAŞARDIK, KURTULDUK!",
      'ending_utopia': "Erzaklarımızı sırtlandık ve {char} rehberliğinde Gizli Yeraltı Kolonisine ulaştık. Burada yeni bir hayat başlıyor. KAZANDINIZ!",
      'ending_utopia_fail': "HAYAL KIRIKLIĞI! {char} koloniyi buldu ama içeri kabul edilmemiz için yanımızda en az 5 Su ve 5 Çorba götürmemiz gerektiğini söylediler. Erzak yetersizliğinden geri çevrildik.",
      'expedition_success_pharmacy': "BAŞARI! {char} eczaneden İlk Yardım Kiti ve Su buldu!",
      'expedition_success_hardware': "BAŞARI! {char} nalburdan Alet Çantası buldu!",
      'error_cache_read': "Önbellek okuma hatası: {e}",
      'unknown_region': "Bilinmeyen Bölge",
'''

en_events = '''      'event_army_fake': "Voices from outside! They are hitting the hatch. 'Army units, open up!' Are we saved?",
      'action_open_hatch': "Open Hatch",
      'event_roaches': "Giant, glowing mutant cockroaches are attacking our soup cans!",
      'event_roaches_killed': "We crushed them all. Our supplies are safe.",
      'event_roaches_left': "The bugs couldn't open the cans and left on their own! We're lucky.",
      'event_roaches_stole': "The bugs ate 2 of our soups and left...",
      'event_vent_broken': "The bunker's ventilation broke down. Toxic air is leaking in.",
      'event_vent_fixed': "It was hard but we fixed it. Our lungs are celebrating.",
      'event_vent_sick': "Air quality is terrible, everyone got sick.",
      'event_raiders': "BANG! BANG! The bunker hatch is being pounded at night. Sounds like raiders!",
      'event_raiders_scared': "We fired a shot into the air. The footsteps ran away.",
      'event_raiders_stole': "They broke the hatch and rushed in! They stole some of our supplies (2 Water, 2 Soup).",
      'event_gas_leak': "A loud hissing sound is coming from the old pipes on the wall. Choking gas is leaking into the bunker!",
      'action_plug_rags': "Plug with Rags",
      'event_gas_tired': "We spent all night breathing toxic gas trying to plug the crack with rags. The leak stopped but we're exhausted, one of us got sick.",
      'event_sus_cans': "We found two unlabelled cans with bulging lids behind the boxes in the corner. Should we add them to our supplies?",
      'action_add_stock': "Add to Stock",
      'event_cans_good': "The cans are still good! Our food increased (+2 Soup).",
      'event_cans_bad': "Bad idea. The cans were punctured, the foul smell made one of us sick.",
      'action_throw_away': "Throw Away",
      'event_cans_thrown': "Not worth the risk. We threw them away.",
      'event_madness': "The dark and silence of the bunker is slowly affecting our sanity. Someone is talking to themselves in the corner.",
      'event_madness_cured': "We talked about the good old days. It was hard but we pulled through.",
      'log_quiet_day': "Day {day}. A quiet wait continues in the bunker. We must use our resources sparingly.",
      'log_expedition_start': "{char} headed out to the {dest}. Hope they return safely.",
      'ending_heli': "I can't believe it! A rescue helicopter landed right on the bunker! {char} cleared the way. WE DID IT, WE'RE SAVED!",
      'ending_utopia': "We packed our supplies and reached the Secret Underground Colony guided by {char}. A new life begins here. YOU WON!",
      'ending_utopia_fail': "DISAPPOINTMENT! {char} found the colony but they said we need at least 5 Water and 5 Soup to be accepted. We were turned away due to lack of supplies.",
      'expedition_success_pharmacy': "SUCCESS! {char} found a Medkit and Water at the pharmacy!",
      'expedition_success_hardware': "SUCCESS! {char} found a Tool at the hardware store!",
      'error_cache_read': "Cache read error: {e}",
      'unknown_region': "Unknown Region",
'''

loc_content = loc_content.replace("'place_military':", tr_events + "      'place_military':", 1)
loc_content = loc_content.replace("'place_military':", en_events + "      'place_military':")

with open(r'c:\Projeler\bunker_60\lib\localization.dart', 'w', encoding='utf-8') as f:
    f.write(loc_content)
